cloudferrylib/os/compute/nova_compute.py
AV zones excluded from create_params of instance in nova_compute resource, because we can have different AV zones on destination cloud.
=> AV zones excluded from create_params of instance

README.md
Get rid of simple duplicating. We shouldn't have to maintain both
README.md and requirements.txt synchronized anymore.
According to conversation in #110.
=> Minor fix: Remove requirements from README.md

cloudferrylib/scheduler/scheduler.py, dry_run/chain.py, tests/scheduler/scheduler.py
Rollback patch modified scheduler constructor signature but did not
modify all the calling code according to new signature. This patch fixes
all these cases and adds several test cases which verify the correctness
of rollbacks.
=> SAIC-86 Fix broken rollback

README.md, cloudferrylib/os/network/neutron.py, configs/config.ini, requirements.txt
- Test networks migration from Grizzly (Quantum) to Icehouse (Neutron).
Result: Networks migrated successfully
- Fix README.md
- Delete obsolete TODO's about Quantum
=> SAIC-27: Quantum support

cloudferrylib/os/network/neutron.py, tests/cloudferrylib/os/network/test_neutron.py
This is for the issue SAIC-89.
CF sometimes uses wrong Segmentation ID, causing public network creation failure.
The reason for this issue is that CF does not record segmentation ID for internal network. Instead, it uses next the available one.
If a privat network is created before public network, it will take the ID 1000.
If the source cloud's public network has vlan-id 1000, then the following error will occurs.
To fix this, we record also the old vlan-id used by internal networks in the source cloud, so there won't be a conflict during migration.
=> SAIC-89, keeping all network vlan-id in migration

cloudferrylib/os/actions/prepare_networks.py, cloudferrylib/os/network/neutron.py
Since the creation order of a DHCP port and an instance port can be
random, sometimes, the DHCP port can take the IP used by an instance
in source could. To avoid it, this fix will disable DHCP and free its
IP before instance port creation, then re-enable the DHCP.
=>  SAIC-97, To avoid DHCP taking IP used by an instance

cfglib.py, cloud/grouping.py, cloudferrylib/os/actions/get_filter.py, cloudferrylib/os/compute/nova_compute.py, cloudferrylib/os/network/neutron.py, cloudferrylib/utils/utils.py, configs/config.ini, configs/groups.yaml, fabfile.py, tests/cloud/test_grouping.py, tests/cloudferrylib/os/compute/test_nova.py
- add 'get_group' task into the fabfile
- provide file config/groups.yaml with the grouping rules
- add new parameter to the config.ini's migrate section (group_file_path)
- implement grouping engine for VMs.
- implement nested gropings support.
- at this moment tenant or network (or both together) are supported as
grouping params.
- extend nova resource functionality:
- add possibility to get instances list by tenant's id or network's name
- add 'get_networks_list' method to the neutron resource
=> Saic 12: Group VMs

cloudferrylib/os/storage/cinder_storage.py
Fix provides __patch_option_bootable_of_volume (cinder resource) method with mysqlconnector, because it used "not direct" interaction with DB (via ssh to DB node and performing bash command).
In some cases it could lead to failure, because we can't connect to DB host from mysql section of config via ssh:
f.e. in case of HA architecture, we can connect to DB through Public VIP with mysqlconnector, but we can't ssh to this ip address.
=> Fix for __patch_option_bootable_of_volume method.

tests/scheduler/scheduler.py
Removes unnecessary code tied with Scheduler() internals.
=> Scheduler unit tests cleanup

devlab/utils/repackage_box.sh
Vagrant box repackaging is tedous and error prone. Introduce script
which takes on the much hated boilerplate.
=> Vagrant box repackage script

cloudferrylib/base/__init__.py, cloudferrylib/base/action/converter.py, cloudferrylib/os/__init__.py
All other files in the directory have path defined:
grep "import action" *
converter.py:import action
copy_var.py:from cloudferrylib.base.action import action
create_reference.py:from cloudferrylib.base.action import action
get_info_iter.py:from cloudferrylib.base.action import action
is_end_iter.py:from cloudferrylib.base.action import action
is_option.py:from cloudferrylib.base.action import action
merge.py:from cloudferrylib.base.action import action
rename_info.py:from cloudferrylib.base.action import action
transporter.py:from cloudferrylib.base.action import action
=> SAIC-105 missing path to import "action"

cfglib.py, cloudferrylib/os/network/neutron.py, configs/config.ini
Add availability to migrate all networks with flag 'all_networks=True'
in the 'migrate' section of config. In case of 'all_networks=False' only
networks, related to tenant specified in the 'src' section of config,
will be migrated.
=> SAIC-96: Add flag 'all_networks' to config

cfglib.py, cloudferrylib/os/compute/nova_compute.py, configs/config.ini, tests/cloudferrylib/os/compute/test_nova.py
Add availability to migrate all VMs with flag 'all_vms=True' in the
'migrate' section of config. It is possible if destination user,
specified in the 'dst' section of config, has admin role in all
destination tenants, otherwise it will fail with 'Unauthorized' error
(Actually, it was required by CloudFerry before to migrate instances
to the different from 'admin' tenant).
=> SAIC-95: Add flag 'all_vms' to config

devlab/Vagrantfile
Adds hostnames to /etc/hosts for all VMs so that CloudFerry scripts
could reach destination using hostname, not just IP address.
=> SAIC-166 Add hostnames to devenv VMs

cloudferrylib/os/compute/nova_compute.py
Sometimes in get_instance response key "security_groups" is absent.
This patch makes safe receiving of security_groups with nova's response.
=> SAIC-167: Fix bug with nova security groups

devlab/utils/repackage_box.sh
Public keys are inserted correctly, but since VMs are shutdown
immediately after the filesystem modification, the data is not stored.
Call `sync` to fix that.
=> Fix ssh keys insertion in box-repackage script

cloudferrylib/os/compute/nova_compute.py
In case SRC has VMs with ERROR state, migration procedure fails accessing
the compute host where the VM is expected to be run. This patch fixes
the issue by verifying the VM is not in error state.
=> SAIC-190 Fix VM migration for VMs with ERROR state

cloudferrylib/os/network/neutron.py
Since this method is unused, obsolete and duplicate - it has been simply
deleted from cloudferrylib/os/network/neutron.py.
=> Minor: Get rid of 'get_security_groups_list' method

cloudferrylib/os/actions/transport_compute_resources.py, cloudferrylib/os/actions/transport_instance.py, cloudferrylib/os/compute/instances.py, cloudferrylib/os/compute/keypairs.py, cloudferrylib/os/compute/nova_compute.py, cloudferrylib/os/identity/keystone.py, scenario/migrate.yaml, scenario/tasks.yaml, tests/cloudferrylib/os/actions/test_keypair_migration.py, tests/cloudferrylib/os/compute/test_nova.py
Key pairs are only accessible by user created them, admin user has no
access to user key pairs. Because of that migration fails for non-admin
VMs which have keypair associated.
=> SAIC-169 Key pair migration

cloudferrylib/os/identity/keystone.py, cloudferrylib/os/image/glance_image.py, tests/cloudferrylib/os/identity/test_keystone.py, tests/cloudferrylib/os/image/test_glance_image.py
In some configurations there are no availability to retrieve OpenStack
services list via Keystone. But Glance authentication was completely
dependent on the services manipulations via Keystone API. That's why we
need to change the way of the Glance authentication. From now it gets
public endpoint URL directly using service type (image).
Also, 'get_endpoint_by_service_type' method was added to Keystone
resource.
=> SAIC-207: Change Glance client authentication process

cloudferrylib/os/identity/keystone.py, cloudferrylib/os/storage/cinder_database.py
In case volume is associated with non-existing tenant/project migration
failed with `NotFound` error message originated from keystone. This
patch fixes this by replacing non-existing tenant name with admin
tenant.
=> SAIC-222 NFS volume migration for non-existing tenant

cfglib.py, cloudferrylib/os/compute/nova_compute.py, cloudferrylib/os/network/nova_network.py, condensation/scripts/nova_collector.py, configs/config.ini, tests/cloudferrylib/os/compute/test_nova.py
All instances and hypervisors assumed hosts are always
accessible which resulted in SSH connection issues in case
node hosting VM is actually down or not accessible. This patch
fixes this by introducing new checks to verify the node is not
down.
=> SAIC-214 Ignore hosts in down state

cfglib.py, cloudferrylib/scheduler/scenario.py, configs/config.ini, devlab/config.ini, devlab/config.template, devlab/provision/cloudferry.sh, devlab/provision/generate_config.sh, devlab/tests/migrate.yaml, fabfile.py
Config options added:
- `migrate.scenario`: allows specifying migration scenario path
- `migrate.tasks_mapping`: allows specifying tasks mapping, which is
then used in migration scenario file
Also updated devlab environment to support custom migration scenario.
=> SAIC-171 Make migration scenario configurable

cloudferrylib/os/image/glance_image.py, tests/cloudferrylib/os/image/test_glance_image.py
From now, all images created in the tenant, that currently does not
exist (f.e. has been deleted), will be bound to tenant, specified in
the src/dst section of config.
=> SAIC-228: Fix `get_image_info` for non-existing tenants

cloudferrylib/scheduler/scenario.py
Check if scenario is correct. Can catch following errors:
* duplicating active tasks
* links on inactive tasks or on not presented tasks
* using tasks which not described in tasks.yaml
=> Check scenario before run migration

cloudferrylib/os/actions/check_bandwidth.py, cloudferrylib/utils/drivers/ssh_chunks.py
Fix binding to slash ('/') in the path of temporary directories, defined
by user in the config. So, from now there is a possibility to specify
there path either with the slash in the end of temp dir path
(f.e. '/tmp/') and without it (f.e. '/tmp').
=> Fix bug with temporary directories path

cloudferrylib/os/image/glance_image.py
From now, all images members created in the tenant, that currently does
not exist (f.e. has been deleted), will be bound to tenant, specified in
the src/dst section of config.
=> SAIC-252: Fix `get_members` for non-existing tenants

README.md, devlab/provision/cloudferry.sh
pip>=7.0.0 causes fabric to miss dependencies (paramiko). This patch
fixes pip version used throughout the code.
=> SAIC-260 Fabric dependency resolution with pip>=7.0.0 fix

cloudferrylib/os/actions/start_vm_if_needed.py, cloudferrylib/os/actions/transport_instance.py, cloudferrylib/os/compute/nova_compute.py, devlab/tests/migrate.yaml, scenario/migrate.yaml, scenario/tasks.yaml
Overview
-------------------
Currently cloudferry sets VM state to ACTIVE regardless of original VM state. This should be modified to keep original state on DST.
See http://docs.openstack.org/developer/nova/devref/vmstates.html for VM states reference.
States to support (DST must have VMs in the same state as on SRC):
-------------------
- Active
- Shutoff/Stopped
- Stopped
- Resized (?)
Special case:
-------------------
- Suspended
- Paused
For these states:
States which are *not* migrated (VMs are simply skipped):
-------------------
- Error
- Build
- Deleting
- Soft deleted
- Rescued
Instances which are not migrated must be noted in the logs
States transfer map
-------------------
Source VM state|Dest VM state
------------ | -------------
Active|Active
Shutoff/Stopped|Shutoff/Stopped …
=> [SAIC-192] VM migration should transfer VM state

cloudferrylib/os/image/glance_image.py
From now, we get only those members, that are related to images we are
going to migrate, instead of all images.
=> SAIC-253: Fix images members issue

cloudferrylib/os/compute/nova_compute.py, tests/cloudferrylib/os/compute/test_nova.py
We can't change VM state from `paused` to `shutoff` and from `suspended` to `shutoff` directly. Only throught `active` state.
Also `suspend` status (as already implemented) does not match with `suspended` state which come from OpenStack. It works at least with Grizzly and Icehouse.
=> Fix for [SAIC-192]. Allow to work with suspended and paused state.

cloudferrylib/base/exception.py, cloudferrylib/os/image/glance_image.py
Image can be deleted directly from the backend and there is a situation
can occur, when Glance doesn't know about it and continues to consider
that everything is fine. So, from now we will skip such images and will
not migrate them.
=> SAIC-278: Fix issue with unreachable images data

devlab/provision/generate_config.sh
This patch defines error_exit function to produce correct error for
invalid user input.
=> SAIC-285 generate_config does not have error_exit defined

cloudferrylib/os/compute/nova_compute.py
Since now we have keypairs migration implemented in the different
specific task, we do not need to collect information about them
in the compute resource anymore.
=> Minor fix: Delete obsolete code in nova_compute

cloudferrylib/os/identity/keystone.py, tests/cloudferrylib/os/identity/test_keystone.py
If keypair was created with user, that has been deleted, we use source
admin user (that is specified in the config) as a default for such
keypairs. But in this case we can face up with 2 situations:
- when source and destination admin users, specified in the config, are
not the same;
- If there is no such admin user on the destination, as on source.
In these cases destination admin user, specified in the config, will be
set up as default for such keypairs.
=> Minor fix: Use destination user as default for keypairs

cfglib.py, cloudferrylib/os/compute/nova_compute.py, configs/config.ini, devlab/config.template, tests/cloudferrylib/os/compute/test_nova.py
Not always CloudFerry node has remote root access to the source and/or
destination clouds databases. And not always all OpenStack services
databases are located on the same host. This patch provides possibility
to specify custom settings (driver, host, user, password, database name)
to the Nova compute databases for both src and dst clouds.
=> SAIC-270: Implement custom DB settings for compute

cloudferrylib/os/actions/check_needed_compute_resources.py, cloudferrylib/os/actions/map_compute_info.py, cloudferrylib/os/compute/instances.py, cloudferrylib/os/compute/nova_compute.py
The process of migration instances is failed
if their flavor was removed previously. The
fix is to create the same flavor on the
destination environment. Appropriate flavor
information is getting from the DB.
=> Fix for [SAIC-269]: recreate removed flavor on dest

devlab/utils/repackage_box.sh
The code in box repackage script relied on having public key stored in
vagrant directory. This patch removes this dependency and generates
public key from private key in case public key does not exist.
=> Box repackage script creates public key if it doesn't exist

devlab/tests/generate_load.py, devlab/tests/test_resource_migration.py
I do not use validate_resource_parameter_in_dst because i want to make sure that quotas were migrated to proper tenant.
=> Added test for tenants quota migration

cloudferrylib/os/actions/snapshots.py
Fix small issue in the MysqlDump. Currently, if there is no destination
cloud's public ssh key in the '~/.ssh/known_hosts' of the CloudFerry
node, we have a prompt for the user to confirm the establishment of
connection to the cloud to perform MysqlDump action. This fix avoids
this prompt and adds cloud's public ssh key to the 'known_hosts'
automatically.
=> Minor fix: Disable 'scp' strict host key checking

cloudferrylib/os/identity/keystone.py, cloudferrylib/os/storage/cinder_database.py
If volume has entry with the non-existing user, we will set up user by
default for it. It will be user, specified in the config.
=> SAIC-298: Fix WriteVolumesDb for non-existing user

cloud/grouping.py, cloudferrylib/utils/utils.py, tests/cloud/test_grouping.py
Now grouping based on network id.
=> [SAIC-280] Grouping may produce invalid results if tenant has multiple networks with the same name

cloudferrylib/os/network/neutron.py
The issue is that the migration process is failed when there is
security group for service tenant on SRC but there is no one on
DST for service tenant. A new check provides an empty list of
rule hashes for further step and rules will be created as usual.
=> Fix for [SAIC-276]: migration fails for neutron security group rules

cloudferrylib/os/actions/image_snapshot.py, devlab/tests/migrate.yaml, scenario/tasks.yaml
Rollback for glance images should not only delete DB records, but also delete copied images.
=> [SAIC-245] Glance image rollbacks

cloudferrylib/os/actions/check_ssh.py, devlab/tests/migrate.yaml
checkSSH uses remote runner and raised exception if needed.
Changed migrate scenario: run all checks before creating snapshot.
=> Fixed SAIC-322: CF failed on checkSSH step

devlab/tests/config.py, devlab/tests/filtering_utils.py, devlab/tests/generate_load.py, devlab/tests/test_resource_migration.py, devlab/tests/test_vm_migration.py
Updated generate load in order to generate filter file, and create
images with more than one member. Updated config.py file with data
required for this scenario. Added one more VM which will not be
migrated in order to verify filtering procedure by instances.
Updated test cases related to testing of resources that will be or
will not be migrated according to filtering procedure. Added a
file with migration utils methods.
=> Added filtering procedure verification.

cloudferrylib/os/network/neutron.py
Fixed neutron.py in order to return subnet info of external net
'shared_net'.
=> Updated neutron.py to return subnet info of external net

requirements.txt
Specified oslo.config version to be instaled, because oslo.config
got updated and is breaking migration process.
=> Specified oslo.config version to be instaled.

cloudferrylib/os/compute/nova_compute.py
When you try to run CF with non-existing VM id in filter config it will fail with:
> NotFound: Instance could not be found (HTTP 404) (Request-ID: req-5cb28e1c-8bab-40ac-ba57-29a96e475791)
This pull makes the error more useful:
>  NotFound: No server with ID of '<some id>' exists.
=> [SAIC-266] CF fails when try to filter by non-existing VM id

cloudferrylib/os/actions/check_ssh.py, cloudferrylib/os/compute/nova_compute.py
Add new `get_compute_hosts` method to the Nova Compute resource and use
it in the `check_ssh` action. This was done because we actually need to
operate computes in this check, but not hypervisors.
Also, `get_hypervisors` method has been deleted from `nova_compute`
resource, because it is not used anywhere else in the project.
=> [SAIC-349] Fix `skip_down_hosts` for `check_ssh`

cloudferrylib/os/compute/nova_compute.py, requirements.txt
Also, `update_default_quotas` method from `nova_compute` resource has
been fixed due to new version of Nova client.
=> [SAIC-349] Update python-novaclient to version 2.16.0

cfglib.py, cloudferrylib/os/actions/prepare_networks.py, cloudferrylib/os/compute/nova_compute.py, cloudferrylib/os/identity/keystone.py, cloudferrylib/os/image/glance_image.py, cloudferrylib/os/network/neutron.py, cloudferrylib/os/network/nova_network.py, cloudferrylib/os/storage/cinder_database.py, cloudferrylib/os/storage/cinder_storage.py, devlab/config.template, tests/cloudferrylib/os/compute/test_nova.py, tests/cloudferrylib/os/identity/test_keystone.py
Allows floating IP migration with IP addresses reserved.
Process:
1. Create floating IP using neutron APIs;
2. Update neutron database using SQL with correct address.
When admin user gets added to a tenant as member, all it's current tokens get revoked. This is the primary reason for replacing all the openstack services client code to not use single token, but generate one on each operation instead.
=> SAIC-312 Floating IP migration

cloudferrylib/os/network/neutron.py, tests/cloudferrylib/os/network/test_neutron.py
In case network on source has incorrectly defined CIDR, migrated network
will have CIDR changed to correct, which will break the network
comparison.
Example:
- source net CIDR: 64.143.228.11/22
- migrated net CIDR: 64.143.228.0/22
In the given example networks are the same, yet CF incorrectly compares
equality of these networks by their string representation.
This patch fixes this behavior.
=> SAIC-337 Same networks have different hashes

cloudferrylib/os/actions/transport_instance.py, cloudferrylib/os/compute/nova_compute.py
This is required for nova instance to boot correctly with non-admin
tenant.
=> Adds admin user to non-admin tenant role for longer period

cloudferrylib/os/identity/keystone.py
Fixes role migration for admin user. Previously if admin was added to a
tenant as member all the auth tokens exipred and migration process
failed. This patch uses new keystone clien for each request so we don't
have that problem anymore and all roles are migrated successfully.
=> Role migration for admin user

cloudferrylib/os/compute/nova_compute.py
Actual error appeard due to invalid environment set. The fix is not
applicable, and must be done by setting up environment properly.
This reverts commit 489330c446704f46304e8897bc38e598a837d031.
=> Revert "Default nova quotas migration fix"

devlab/Vagrantfile
It was found by testing that there is enough 2,5GB of RAM for Source and Destination VMs and 1,5Gb for CloudFerry VM.
=> Decreased RAM for Vagrant VMs

cloudferrylib/os/actions/check_needed_compute_resources.py, cloudferrylib/os/compute/nova_compute.py, tests/cloudferrylib/os/compute/test_nova.py
The issue was caused by invalid novaclient.flavors.get() behavior, which
returns deleted flavors if flavor ID matches. Replaced with
novaclient.flavors.find(), which raises 404 `NotFound` if flavor is
deleted.
=> SAIC-405 Fix nova flavor migration

cloudferrylib/os/compute/nova_compute.py, tests/cloudferrylib/os/compute/test_nova.py
Fixes issue when rolling back failed migration fails itself with `KeyError`.
The issue appeared because there was no transition from 'shutdown' to
'verify_resize' state defined in code.
=> SAIC-400 Rollback for VM in 'verify resize' state

devlab/Vagrantfile
Decreased CPU usage limit from 100% to 80% and increased RAM for icehouse VM to 3G
=> Tweak vagrant settings for VMs

devlab/config.template
This change need to be done to prevent CI system to fail builds because
of slow network connectivity between VMs
=> Decrease speed_limit in config.template

cloudferrylib/os/compute/nova_compute.py, tests/cloudferrylib/os/compute/test_nova.py
Picks random host if nova-scheduled compute node fails to boot VM. This is
useful in case one of the nodes in cluster is displayed to nova as operational,
but is faulty in reality.
=> SAIC-390 Schedule VM boot host manually on error

devlab/jenkins/functional_tests.sh
We delete only VMs created by current Jenkins build
=> Modify vagrant VMs' deleting procedure

requirements.txt
This patch download custom paramiko from my github-repo, because native paramiko has bug(race condition)
Issue - https://github.com/paramiko/paramiko/issues/570
Pull - https://github.com/paramiko/paramiko/pull/571
=> [SAIC-239] Fix requirements.txt for download custom paramiko

devlab/tests/data_collector.py
Data collector will not collect info about when VM was updated,
because it will be updated anyway during rollback, thats why this
data was excluded from collected_data dict in order to avoid errors.
=> Fixed data_collector script, to collecect only required data.

requirements.txt
Removes SSL warning generated by urllib when trying to access insecure
HTTPS endpoints. See https://urllib3.readthedocs.org/en/latest/security.html#insecurerequestwarning
=> SAIC-395 Remove SSL warning

QUICKSTART.md
Devlab was recently updated with separate NFS server which is used as a
backend for cinder in openstack VMs. This change was not reflected in
quickstart guide, which this patch fixes.
=> Add NFS server to quickstart documentation

cloudferrylib/os/actions/convert_compute_to_image.py, cloudferrylib/os/actions/convert_file_to_image.py, cloudferrylib/os/actions/is_boot_image_deleted.py, cloudferrylib/os/actions/recreate_boot_image.py, cloudferrylib/os/image/glance_image.py, cloudferrylib/utils/qemu_img.py, cloudferrylib/utils/ssh_util.py, devlab/tests/scenarios/cold_migrate.yaml, scenario/tasks.yaml
Example output when no backing file:
INFO     [/home/segorov/projects/CloudFerry/cloudferrylib/scheduler/scheduler.py : lineno 47]  08-26 17:30:10  -------- Start task: BaseTask|ConvertComputeToImage
ERROR    [/home/segorov/projects/CloudFerry/cloudferrylib/os/image/glance_image.py : lineno 310]  08-26 17:30:11  Image has not been found
WARNING  [/home/segorov/projects/CloudFerry/cloudferrylib/os/actions/convert_compute_to_image.py : lineno 74]  08-26 17:30:11  No boot image for instance, need to re-create it
INFO     [/home/segorov/projects/CloudFerry/cloudferrylib/scheduler/scheduler.py : lineno 51]  08-26 17:30:11  -------- End task: BaseTask|ConvertComputeToImage
INFO     [/home/segorov/projects/CloudFerry/cloudferrylib/scheduler/scheduler.py : lineno 47]  08-26 17:30:11  -------- …
=> Fixed SAIC-165: re-create deleted image on dst

devlab/config.ini
src_ip and dst_ip are used for devlab instead of grizzly_ip and icehouse_ip
=> Fixed blocker issue for devlab

configs/config.ini, devlab/config.template
This is Fix for SAIC-436. Add service_tenant parameter to [src] and [dst] and description what is this parameter and how to obtain the values.
=> Fix for SAIC-436. Add service_tenant parameter to [src] and [dst]

fabfile.py
Added warning log to evacuation Fabric task for cases, when:
- there is only 1 compute node in cloud configuration;
- compute nodes cannot be freed;
- error has been occurred during retrieving information about nodes,
that should be freed.
=> [SAIC-310] Improve evacuate logging

cloudferrylib/os/network/neutron.py, cloudferrylib/utils/mysql_connector.py
Steps for FloatingIP migration:
- Allocate FloatingIP on dst
- Change FloatingIP in database:
- Change IP in `floatingips` table
- Change IP in `ipallocations` table *(added in this patch)*
- Delete related rows from `ipavailabilityranges` table for avoid FloatingIP duplication *(added in this patch)*
=> [SAIC-442] FloatingIP migration creates another IPs on dst

devlab/Vagrantfile, devlab/provision/fix_interfaces.sh
Added physical eth1 interface to the floating bridge. This allow access
to the vm's inside of OpenStack directly from the host-server.
=> Fixed floating ip network in grizzly and icehouse

cfglib.py, cloudferrylib/os/actions/snapshots.py, cloudferrylib/utils/mysql_connector.py, tests/cloudferrylib/utils/test_mysql_connector.py
Allows user to specify particular MySQL backend host when MySQL is deployed
on multiple nodes, and multiple MySQL nodes are hidden behind a VIP. In this
scenario providing VIP in `config.dst_mysql.db_host` will break mysqldump
which requires to be run locally on particular DB host. Patch allows to specify
`config.migrate.mysqldump_host` which workarounds this problem.
=> SAIC-468 Config option for DB backend host

configs/config.ini
Adds description of `mysqldump_host` config option to config.ini. New
config option Allows to specify host for creating MySQL dump used in rollback
procedure. Useful when MySQL uses multinode configuration with load balancer in front.
In this case one would set VIP hostname in `[dst] db_host` and specific
SSH-accessible MySQL node behind VIP for creating MySQL dump used in
rollback.
=> SAIC-462 MySQL host config description

cloudferrylib/os/network/neutron.py
Case when change_router_ips=False and clean_router_ips_stub=True.
=> [SAIC-486] change_router_ips=False crush migration

devlab/tests/config.py, devlab/tests/functional_test.py
During CF functional Testing, wrong behaviour with test "test_migrate_neutron_networks under resource migration"
I have generated the load on source but migration is not initiated.
In this case when I check available networks on source and destination side then they are different (As migration is not initiated). In this case this test should fail.
But test is showing success. Please check below -
(.venv)root@cloudferry:/home/vagrant/CloudFerry# nosetests -sv devlab/tests/test_resource_migration.py:ResourceMigrationTests.test_migrate_neutron_networks
test_migrate_neutron_networks (tests.test_resource_migration.ResourceMigrationTests) ... src_nets {'networks': []}
dst_nets {'networks': [{u'status': u'ACTIVE', u'subnets': [u'8dcc195b-56af-4f19-b3f2-211403e92784'], u'name': u'public', …
=> Fix propsed for SAIC-480 & SAIC-488

cloudferrylib/os/actions/check_networks.py, tests/cloudferrylib/os/actions/test_check_networks.py
Add networks segmentation id checking to the `check_networks` action.
Patch provides handling duplicates in segmentation ids. If busy
segmentation id is found on the destination, raise exception.
=> [SAIC-458] Add networks segmentation id check

cloudferrylib/os/identity/keystone.py
Fixes error during migration when the same role already exists on
destination for any reason.
=> SIAC-521 Existing role migration

cloudferrylib/os/actions/detach_used_volumes_via_compute.py
Resolves issue caused by refactoring done for the `wait_for_status`
method. Invalid number of arguments were passed to the method.
=> SAIC-534 Detach volume from compute

cloudferrylib/os/network/neutron.py
Fix issue with Neutron networks migration for cases, when network has
attribute `provider:physical_network`.
=> [SAIC-531] Fix networks migration

cloudferrylib/os/network/neutron.py
When admin tenant is specified in filter.yaml config neutron object
migration failed with 400 "Duplicate subnet error". This patch resolves
the issue.
=> SAIC-548 Duplicate admin subnets

cloudferrylib/os/actions/convert_compute_to_image.py, cloudferrylib/os/actions/convert_file.py, cloudferrylib/os/actions/convert_volume_to_image.py, cloudferrylib/os/actions/pre_transport_instance.py, cloudferrylib/os/actions/upload_file_to_image.py, cloudferrylib/os/identity/keystone.py, cloudferrylib/os/image/filters.py, cloudferrylib/os/image/glance_image.py, cloudferrylib/utils/filters.py, tests/cloudferrylib/os/actions/test_converter_volume_to_image.py, tests/cloudferrylib/os/image/test_image_filters.py, tests/cloudferrylib/utils/test_filters.py
When migration is filtered by tenant, only filtered tenant migrated
originally.  Glance images which belong to tenants which are not
specified in filter were not migrated and this caused glance image
migration. This patch resolves this issue and refactors filter logic
separating it from migration.
=> SAIC-435,436,503,504 Non-filtered image migration

cloudferrylib/os/network/neutron.py
Remove redudant and bugs-forming check in the `upload_floatingips`
method of `NeutronNetwork` resource. There are two reasons for it:
1. We have wrong tenant id to compare (we try to compare tenant_id
from source with tenant_id on dest and of course they are different,
because we do not migrate original tenants IDs);
2. We already performed this filtering, when obtained information about
migrated Neutron items (filtering has been already done in the
`read_info` method, so we do not need to do this twice).
=> [SAIC-481] Fix Floating IPs filtering

devlab/provision/generate_config.sh
Added compatibility for BSD sed so that generate_config.sh can be used
on OSX.
=> SAIC-559 OSX compatibility for generate_config.sh

cloudferrylib/os/actions/check_networks.py, cloudferrylib/os/network/neutron.py, tests/cloudferrylib/os/actions/test_check_networks.py, tests/cloudferrylib/os/network/test_neutron.py
Add floating IPs checking to the `check_networks` action. Patch provides
handling duplicates in floating IPs. Check if floating IP overlaps with
the destination cloud. If floating IP is exactly the same as on the
source cloud (checking by address, tenant, network) check passes. If
difference have been found - exception  will be raised.
Also check if floating IP is not busy (i.e. is not associated to VM on
SRC and DST at the same time) on both environments.
=> [SAIC-477] Add floating IPs check

devlab/tests/functional_test.py
Drops `paramiko.transport` debug logs when functional tests are run.
These have no value to the user and only complicate funtional test
failures.
=> Removes unnecessary paramiko debug logs from tests

cloudferrylib/os/storage/cinder_storage.py, requirements.txt
Python-cinderclient has updated from 1.0.9 to 1.1.0
version to have an ability to change bootable flag of volume.
__patch_option_bootable_of_volume, which uses mysqlconnector
replaced by api call
=> upgrade of python-cinderclient version

cloudferrylib/base/resource.py, cloudferrylib/os/identity/keystone.py, cloudferrylib/os/image/glance_image.py, cloudferrylib/os/network/neutron.py, cloudferrylib/utils/cache.py, tests/cloudferrylib/os/identity/test_keystone.py, tests/cloudferrylib/os/network/test_neutron.py, tests/cloudferrylib/utils/test_cache.py
Previously network migration logic assumed external networks only belong to admin tenant,
which is not the case for the most production environments. This patch adds support for
floating IPs allocated in external networks which belong to different tenants.
=> SAIC-540 Floating IP allocated in different external networks

cloudferrylib/os/identity/keystone.py, tests/cloudferrylib/os/identity/test_keystone.py
When we get keystoneclient instance using only user/pass credentials, during further operations keystone client will use internal endpoint for API requests. This way we need to have an access internal cloud network from CF host and it brake initial conceptions of CF tool 'use only public network'. This fix adds additional authorization of keystone client using token and endpoint,which allows us to use some
specific endpoint during API requests.
=> change of keystone client authorization logic

cloudferrylib/utils/files.py
When creating remote temporary directory with "sudo mktemp" further attempt
to scp file to it will fail if scp is done using non-root user. This patch
adds "sudo chown {user} {tmp_directory}" step to temporary remote dirctory
creation process.
=> SAIC-614 chown temporary directory to current user

cloudferrylib/os/network/neutron.py, devlab/tests/functional_test.py, devlab/tests/generate_load.py, devlab/tests/test_resource_migration.py
To get all keypairs, which were created via generate_load.py,
method get_users_keypairs logins under each valid user,
which were created by generate_load.py and takes keypairs.list().
For dst clould, users passords updates according to config.py
(because user passwords migrate not correctly)
=> Fixed keypair filtering in func tests

cloud/__init__.py, cloud/cloud_ferry.py, cloudferrylib/os/actions/convert_file.py, cloudferrylib/os/actions/convert_image_to_file.py, cloudferrylib/os/actions/load_compute_image_to_file.py, cloudferrylib/os/actions/pre_transport_instance.py, cloudferrylib/os/actions/transport_ephemeral.py, cloudferrylib/os/actions/verify_vms.py, cloudferrylib/os/identity/keystone.py, cloudferrylib/os/image/glance_image.py, cloudferrylib/utils/__init__.py, cloudferrylib/utils/remote_runner.py, devlab/tests/functional_test.py, tests/cloud/test_grouping.py
Following flake8 errors were ignored previously:
- F401 - module imported but unused
- F403 - ‘from module import *’ used; unable to detect undefined names
This patch resolves all these issues.
=> Resolves all flake8 issues, including F401 and F403

cloudferrylib/utils/proxy_client.py
Proxy catch exceptions and reraise them. Unfortunately this behavior
hide original stacktrace and due to this it is impossible to understand
what caused error in some cases. So adding warning with exc_info=True
(it will output original exception stacktrace along with warning message)
will help a lot in debugging such errors.
=> Improve client proxy error logging.

cfglib.py, cloudferrylib/os/compute/nova_compute.py, configs/config.ini, devlab/config.template, tests/cloudferrylib/os/compute/test_nova.py
- Previoulsy only hosts known to nova as 'down' were skipped, with this
patch hosts which are 'disabled' are also treated as not available for
migration;
- Removed config option to skip down or disabled hosts, now these hosts
are always skipped;
- Resolved pylint warnings and errors in files modified.
=> Skips down or disabled hosts

cloudferrylib/base/network.py, cloudferrylib/os/network/neutron.py, cloudferrylib/utils/cache.py, configs/config.ini, devlab/config.template, tests/cloudferrylib/os/network/test_neutron.py
Reduce OpenStack Neutron API calls in the `NeutronNetwork's`
`read_info` method. Use caching instead of multiple API calls.
Fix issue with keyword arguments in `utils/cache` module.
Add `get_all_quota` option to all configs.
=> [SAIC-565] Network info retreiving optimization

cloudferrylib/base/resource.py, cloudferrylib/os/compute/nova_compute.py, tests/cloudferrylib/os/compute/test_nova.py
- Increased VM boot timeout to 5 minutes to better handle
possible service outages and longer VM boot times;
- VM scheduler logic improved to use all the possible compute
nodes during VM provisioning: first spawn command simply
tries to create an instance based on nova scheduler, while
all the subsequent boot requests use specific compute nodes.
- Improved logging for `wait_for_status()` and nova boot process.
=> SAIC-658 Random VM scheduling update

cloudferrylib/os/image/glance_image.py, tests/cloudferrylib/os/image/test_glance_image.py
Glance have special property to protect images that are used as "gold master"
from accidental removal. This property is useful in typical OpenStack API
use case, but in case of migration it is good idea to set protected to
false every time we try to remove image.
=> SAIC-629 Unprotect image before delete

cloudferrylib/os/compute/nova_compute.py, cloudferrylib/utils/utils.py
Sometimes libvirt instances can disappear from cloud while staying in nova
database (for example when compute node gets redeployed after failure).
CloudFerry should check if instance exists before migrating it.
=> SAIC-627 Check if instance exists on compute before migrate

cloudferrylib/utils/cmd_cfg.py, cloudferrylib/utils/qemu_img.py, tests/cloudferrylib/utils/test_qemu_img.py
Image re-creation logic used to fail in case ephemeral disk had a link
to an actual ephemeral storage disk, e.g. when `qemu-img info <disk>`
operation returned
```
backing file: /var/lib/nova/instances/<disk path> (actual path: /var/lib/nova/instances/<actual path>)
```
This patch resolve this issue by parsing JSON rather than CLI output.
=> SAIC-672 Handle qemu-img with actual path

cloudferrylib/os/network/neutron.py
In neutron two or more ports can have the same IP address, so it's
incorrect to search for MAC address based only on IP address of port.
This patch makes get_mac_by_ip method to only consider ports that are
connected to VM for which we need to find MAC address.
=> SAIC-737 Fix get_mac_by_ip method for neutron

configs/logging_config.yaml
It's required to add handlers for logger 'paramiko.transport' to exclude log warning "No handlers could be found for logger 'paramiko.transport' "
=> [SAIC-791] Add handlers for logger 'paramiko.transport'

cloudferrylib/os/image/glance_image.py, tests/cloudferrylib/os/image/test_glance_image.py
There was a missed option (insecure) in get_client of image resource.
=> Added missed insecure option to glance image resource

devlab/Vagrantfile, devlab/config.ini
As per current design of Cloudferry, Vagrantfile does not considers
'host behind proxy' problem.
If one is trying to setup Cloudferry devlabs, booted VM will have no Internet
access, as Vagrantfile does consider proxy considerations.
Again, with no internet access it not be able to downloads required packages.
When I tried 'vagrant up juno', devstack was not able to download.
And this was basically because of lack of support of 'behind the proxy'.
This patch eliminates this problem.
=>  "Behind the proxy" support for devlab setup

devlab/Vagrantfile
By default, Vagrant uses the current directory you're in.
So before execution commands, don't forget to change the
working directory of Vagrant.
i.e.:
export VAGRANT_CWD=/path/to/CloudFerry/devlab
=> [SAIC-184] Vagrant commands outside of devlab folder.

scenario/stages/1_checkcloud.yaml, scenario/stages/3_get_and_transfer_images.yaml, scenario/stages/5_network_transporter.yaml, scenario/stages/6_get_transfer_volumes.yaml, scenario/stages/7_transport_keypairs.yaml
Remove `identity_transporter` task from stages scenario to reduce
migration time.
Also remove `preparation` and `rollback` steps from
`scenario/stages/1_checkcloud.yaml`, because `CheckCloud` action
guarantees removal of all objects created in destination.
=> [DO NOT MERGE] Remove unnecessary steps from stages scenarios

devlab/tests/config.py, devlab/tests/generate_load.py, devlab/tests/test_resource_migration.py, devlab/tests/utils.py
Regression of SAIC-725.
Extend functional tests to make sure that cinder volumes in "invalid"
statuses ("creating", "error", "deleting", "error_deleting") are skipped
with no errors.
=> SAIC-727 [FT] Verify invalid cinder volumes skipping

cloudferrylib/os/compute/nova_compute.py, cloudferrylib/utils/node_ip.py, cloudferrylib/utils/utils.py, tests/cloudferrylib/utils/test_node_ip.py
We often faced an issue when user-configured `ext_cidr` option doesn't
match any IP address on a node, which resulted in debug messages like these:
```
DEBUG remote_runner.py:62 "running 'mktemp -d' on 'None' host as user 'root'"
```
This is happening because `ext_cidr` config option doesn't match any IP
address on a node. In order to avoid this, a fallback path was implemented:
if `ext_cidr` doesn't match any IP address on a node, show warning and
return IP address which was used to reach to a particular node.
=> SAIC-788 Fallback to host's IP address if `ext_cidr` doesn't match anything

cloudferrylib/os/network/neutron.py
Skip a security group if its tenant is not found.
=> [SAIC-827] Skip creating security groups for undefined tenants

cloudferrylib/os/actions/check_affinity.py, cloudferrylib/os/actions/get_info_instances.py, cloudferrylib/os/actions/verify_vms.py, cloudferrylib/os/compute/server_groups.py, devlab/tests/scenarios/cold_migrate.yaml, scenario/cold_migrate.yaml, scenario/cold_migrate_autorollback.yaml, scenario/live_migrate.yaml, scenario/migrate_resources.yaml, scenario/migrate_resources_autorollback.yaml, scenario/migrate_vms.yaml, scenario/stages/0_prechecks.yaml, scenario/tasks.yaml, tests/cloudferrylib/os/actions/test_verify_vms.py
Add initial check, which verifies whether source and destination clouds
support affinity and anti-affinity API (Nova server groups). If
affinity/anti-affinity API is not supported - do not start migration and
fail with error message.
Add automated verification that migrated VMs belong to correct Nova
server groups.
Fix issues related to OpenStack versions, that do not support affinity
and anti-affinity API (Nova server groups).
Fix `verify_vms` action as it has not worked properly.
=> [SAIC-743] Add fix, check and verify for Affinity

cfglib.py, cloud/os2os.py, cloudferrylib/os/actions/recreate_boot_image.py, cloudferrylib/utils/drivers/copy_engine.py, configs/config.ini, tests/cloudferrylib/utils/test_copy_engine.py, tests/cloudferrylib/utils/test_file_utils.py
scp was previously used to copy ephemeral storage, which resulted in a
lot of code which does a fraction of what rsync can, while being more
complex to maintain. This patch uses rsync by default, and if rsync is
not available on a target host, falls back ot scp. Ephemeral copy backend
is now also configurable through `[migrate] ephemeral_copy_backend`
config option.
=> Use rsync for ephemeral storage transfer

devlab/tests/generate_load.py, devlab/tests/test_resource_migration.py
Extend functional tests to verify routers are migrated correctly when filtering enabled.
Added test to check router connected to correct networks.
Added test to check router migrated to correct tenant.
=> SAIC-785 Extend functional tests to verify routers

scenario/migrate_vms.yaml
CF doesn't remove broken VMs from destination
because migrate_vms scenarion didn't contain verify step.
Add remove_failed_instances step into verify section.
=> [CF-23] Add verify step into migrate_vms.yaml

cloudferrylib/base/resource.py, cloudferrylib/os/actions/check_cloud.py, cloudferrylib/os/actions/check_filter.py, cloudferrylib/os/compute/cold_evacuate.py, cloudferrylib/os/compute/nova_compute.py, cloudferrylib/os/compute/server_groups.py, cloudferrylib/os/identity/keystone.py, cloudferrylib/os/image/glance_image.py, cloudferrylib/os/storage/cinder_storage.py, cloudferrylib/utils/proxy_client.py
Client proxy catch all exceptions and retry request after waiting for
some time. The problem is that sometimes exception is expected to
occur but proxy client don't know anything about this. So it try to
call API several times before allowing exception to be handled
elsewhere. This results in several WARNINGs shown in log. This
patch fix it by adding special method that can be used to tell
proxy client which exceptions it shouldn't handle.
=> [SAIC-646] Remove excess warnings from log

cloudferrylib/utils/drivers/copy_engine.py
Before copying ephemeral storage using `rsync` CF verifies if `rsync` is
installed by calling `rsync --help` which produces a lot of unnecessary
output. This patch reduces amount of output produced by redirecting it
to `/dev/null`.
=> Removes unnecessary output from rsync

cfglib.py, cloudferrylib/os/compute/nova_compute.py, configs/config.ini, tests/cloudferrylib/os/compute/test_nova.py
When VM boot fails on a host scheduled by nova scheduler, CF tries to
boot it on all hosts in random order, but without availability zone
taken into account. This resulted in hosts picked from random
availability zone. Given patch uses hosts present in availability zone.
=> SAIC-810 Retry VM boot in correct availability zone

cloudferrylib/os/storage/cinder_storage.py
Replaces invalid python `None` values with `NULL`.
=> CF-118 None values in cinder DB

cloudferrylib/os/actions/check_networks.py, cloudferrylib/os/actions/filter_similar_vms_from_dst.py, cloudferrylib/os/compute/nova_compute.py, tests/cloudferrylib/os/actions/test_check_networks.py
Get only ids of instances instead of getting full information
in check_networks action.
=> [SAIC-802] Avoid extra getting an external ip from instances

cfglib.py, cloudferrylib/os/actions/server_group_transporter.py, cloudferrylib/os/storage/cinder_storage.py, configs/config.ini, devlab/config.template, requirements.txt
Pip cannot find and install mysql-connector-python library.
The page https://pypi.python.org/simple/mysql-connector-python/ is empty.
=> [CF-123] Use PyMySQL library instead of mysql-connector-python

devlab/tests/generate_load.py, devlab/tests/test_verify_dst_functionality.py
devlab/tests/test_verify_dst_functionality.py#L102-L105 - deleted duplicated code
Fixed filtering by tenant in the  "wait_vms_deleted" method.
=> CF-119 Fixed tearDown in functional tests

devlab/tests/test_resource_migration.py, requirements.txt, test-requirements.txt
Moved nose to test-requirements.
Removed rednose requirement.
=> CF-129 Fix for runtime warning with rednose dependance.

cloudferrylib/os/actions/filter_similar_vms_from_dst.py, cloudferrylib/os/compute/nova_compute.py
Show warning and skip instances are spawned for deleted tenant on act_filter_similar_vms_from_dst.
=> [CF-130] Skip instances from deleted tenants

cloudferrylib/utils/drivers/copy_engine.py
Resolves invalid rsync options which resulted in ephemeral storage not
being copied over to destination during migration.
=> CF-135 Correct rsync copy arguments

cloudferrylib/base/exception.py, cloudferrylib/base/resource.py, cloudferrylib/os/compute/cold_evacuate.py, cloudferrylib/os/compute/nova_compute.py, cloudferrylib/utils/timeout_exception.py, cloudferrylib/utils/utils.py, tests/cloudferrylib/base/test_resource.py, tests/cloudferrylib/os/compute/test_nova.py
Move TimeoutException from cloudferrylib.utils.timeout_exception to
cloudferrylib.base.exception.
Remove unused ChecksumImageInvalid from cloudferrylib.utils.utils.
=> [CF-43] Move base exceptions to cloudferrylib.base.exception

cfglib.py, cloudferrylib/os/compute/instance_info_caches.py, cloudferrylib/os/compute/nova_compute.py, configs/config.ini, devlab/config.template, tests/cloudferrylib/os/compute/test_instance_info_caches.py, tests/cloudferrylib/os/compute/test_nova.py
Deploy instances and keep the order of interfaces the same as on source.
Add keep_network_interfaces_order option to use new fuctionality.
Implement unit tests.
=> [CF-110] Keep order of interfaces

cloudferrylib/os/actions/check_ssh.py, cloudferrylib/utils/remote_runner.py, tests/cloudferrylib/utils/test_runner.py
Sometime remote runner cannot raise an exception because
remote host waits an additional information.
Example: ssh server waits login and password when we are
connecting by using wrong key pair.
To solve this problem the timeout option has been added
to the RemoteRunner and abort_on_prompts option has been
set as True.
Remove raising AbortMigration error in case of any hosts
are unreacheable.
=> [CF-16] Add timeout and abort_on_prompts options to the RemoteRunner

cloudferrylib/os/actions/check_networks.py, cloudferrylib/os/network/neutron.py, tests/cloudferrylib/os/actions/test_check_networks.py, tests/cloudferrylib/os/network/test_neutron.py
Add allocation pools to subnets hash. From now all networks comparisons
during migration include allocation pools as well as CIDRs.
Add allocation pools verification for external networks to the
`check_networks` action. If allocation pools overlap on source and
destination, migration does not start.
Remove `subnets_hash` from networks hash due to it's irrelevance.
Move CIDR conversion from `get_resource_hash` to the `convert_subnets`
method of `NeutronNetwork` resource.
=> [CF-82] Compare subnets allocation pools

cloudferrylib/os/identity/keystone.py, tests/cloudferrylib/os/identity/test_keystone.py
Looks like tenant names are case-insensitive. E.g. when you try to
create tenant with name "TEST" when tenant with name "test" already
exists, you will get 409 Conflict. But when you try to search tenant
by name using keystone_client.tenants.find(name='TEST') you will
get NotFound exception because find function code don't respect
tenant name case insensitivity. This patch fix this problem by
using get_tenant_by_name method instead of tenants.find.
=> [CF-167] Fix searching tenant by name.

cloudferrylib/os/compute/nova_compute.py
If flavor was deleted and then recreated with same ID, nova will
return old flavor for GET request in grizzly clouds. After this patch
code no longer rely on what nova returned in GET request, and use data
from SQL database instead.
=> [SC-186] Fix copy ephemeral disk when flavor was deleted.

cloudferrylib/base/resource.py, cloudferrylib/os/image/glance_image.py, tests/cloudferrylib/os/image/test_glance_image.py
Filter the deleted images from destination cloud.
Create an image with new id in case the image with same id exists.
=> [CF-181, CF-202] Fix a problem with duplicate images

devlab/provision/cleanup_nova_instances.sh, devlab/provision/qemu.sh
Now we have monit on all our openstack boxes. It can start openstack processes itself.
=> Restart nova-compute instead of start it

cloudferrylib/os/actions/recreate_boot_image.py, cloudferrylib/os/image/glance_image.py, cloudferrylib/utils/drivers/copy_engine.py, cloudferrylib/utils/file_proxy.py, cloudferrylib/utils/files.py, requirements.txt, tests/cloudferrylib/os/actions/test_recreate_boot_image.py, tests/cloudferrylib/utils/test_file_proxy.py
In some case sftp doesn't work, to fix it use dd command by ssh
and read a data from stdout of ssh tunnel.
Implement RemoteStdout class to execute a command and work with
stdout of command.
=> [CF-86] Use dd instead of sftp

cloudferrylib/os/actions/filter_similar_vms_from_dst.py, scenario/migrate_vms.yaml
- Remove task IdentityTransporter from migrate_vms.yaml
- Modify task FilterSimilarVMsFromDST
=> [CF-178] Reduce time to start VM migration

cloudferrylib/os/compute/nova_compute.py, tests/cloudferrylib/os/compute/test_nova.py
Implement get_availability_zone function which returns a default zone
if the original does not exist.
The get_compute_hosts function doesn't check an availability zone.
=> [CF-218] Use a correct availability zone

cloudferrylib/os/actions/check_networks.py, cloudferrylib/os/network/neutron.py
Add 2 types of physnets checks:
1. Check busy physical networks on DST of FLAT network type.
We need this check because FLAT network can be created with one physnet
only once in Neutron. Every next attempt to use the same physnet for
network of such type will be failed.
2. Check physical networks existence on DST for VLAN network type.
We need this check because VLAN network can not be created with physnet,
that does not exist on the terget environment. Every such network
creation attempt will be failed in Neutron.
So we need to prevent these cases and inform about them in the
`CheckNetworks` step at the preparation part of CloudFerry scenario.
=> [CF-102] Add physical networks check

scenario/stages_without_rollback/3_get_and_transfer_images.yaml
This patch removes act_identity_trans task from scenario/stages_without_rollback/3_get_and_transfer_images.yaml.
=> Remove identity from glance with no rollback stage

cloudferrylib/os/compute/server_groups.py
Do not migrate Nova server groups, that are bonded with non-existing
tenants.
=> [CF-212] Fix affinity migration

cloudferrylib/os/actions/convert_compute_to_image.py, cloudferrylib/os/image/glance_image.py
Catch ZeroReturnError and reraise as ImageDownloadError to skip
a broken image.
Add additional log messages.
=> [CF-229] Recreate an image from vm in case of ssl error.

cloudferrylib/os/actions/check_networks.py, cloudferrylib/os/network/neutron.py, tests/cloudferrylib/os/actions/test_check_networks.py
Fix `CheckNetworks` action for cases, when external networks mapping is
enabled and there can be some Network resources overlap, which we accept
and should continue migration process instead of interrupt.
Add existence and validity check of external networks, specified in the
map file (if `ext_net_map` option is enabled).
Fix `NeutronNetwork` log message if external network mapping is enabled.
=> [CF-189] Fix CheckNetworks

cfglib.py, cloudferrylib/os/actions/transport_compute_resources.py, configs/config.ini, tests/cloudferrylib/os/actions/test_keypair_migration.py
Keypairs from deleted tenants and users not suppose to be
migrated under admin tenant. We would like to drop them
from being migrated as there is no need for them.
=> [CF-234] Fix key-pairs from deleted users under admin

cloudferrylib/copy_engines/base.py
Clean_dst has an error with remote runner, it sets the bool value
for string variable "gateway".
=> Fix clean_dst function of BaseCopier

cloudferrylib/os/image/filters.py, tests/cloudferrylib/os/image/test_image_filters.py
Sometimes Glance client returns images list, which contains non-active
images in there (f.e. with such statuses as `queued`, `deleted` etc).
But we do not need to retrieve information about them, cause some
actions try to get them from Glance, but fail in some cases (f.e. if
image status is `deleted`). In other cases data of such images will be
just invalid, so we will not migrate them in any case.
This patch excludes such images from the images list and writes it in
the debug log.
=> [CF-214] Exclude non-active images from migration

devlab/generate_load.py, devlab/tests/config.py
Added `deleted_flavor` flavor which covers this scenario:
- In source cloud
- Create flavor with ID 3 with ephemeral == 0
- Delete flavor
- Create new flavor with the same ID with ephemeral > 0
- Run migration
=> CF-195 check deleted flavors are handled correctly

devlab/generate_load.py, devlab/tests/config.py, devlab/tests/testcases/test_verify_dst_functionality.py
- Generate a number of networks on SRC & DST
- Have internal and external networks with non-overlapping subnets
- Have different segmentation ID
- Generate a number of floating IPs on source
- Generate floating IPs on destination which:
- Have different floating IP address
- Run standard migration
- Verify migration succeeded
=> CF-85 verify Neutron if non-overlapping resources exist on DST

devlab/generate_load.py, devlab/tests/config.py
- Create external network in source cloud
- Create the same external network in destination cloud
- Create several (5) floating IPs in source cloud
- Add following to CloudFerry config:
```
[migrate]
ext_net_map = <source to dest external network mapping>
```
- Run migration
- Verify floating IPs migrated successfully
=> CF-79 Add migration of floating IPs into pre-created networks.

cloudferrylib/os/compute/nova_compute.py
Check that failed instance exists.
=> [CF-294] Fix getting nonexistent instance for deploy_instance function

docs/conf.py, docs/configuration.rst, docs/glance_image_migration.rst, docs/index.rst, docs/nova_compute_migration.rst
Documents migration of non-VM nova objects:
- flavors
- user quotas
- tenant quotas
=> CF-304 Nova compute objects migration documentation

cloudferrylib/utils/retrying.py, tests/cloudferrylib/utils/test_retrying.py
The run function of Retry object has to reset the attempts or total time,
otherwise we cannot use the object as a decorator.
=> [CF-310] Reset retrying during the run function call.

cloudferrylib/os/storage/plugins/copy_mechanisms.py
Steps to reproduce
1. Set invalid path for bbcp executable in `[bbcp] path` config option
2. Run volume migration
3. Notice unhandled exception
4. Put correct value to `[bbcp] path`
5. Run volume migration again
6. Notice volume was skipped as already migrated
Actual behavior
- Volume is skipped as "migrated" even though it's empty
Expected behavior
- Volume should be removed on CopyEngine initialization failure
=> CF-319 Remove non-migrated volumes

tests/cloudferrylib/os/identity/test_keystone.py
Mock os_cli_cmd instead of clients module.
=> [CF-292] Correct mocking for KeystoneIdentityTestCase

devlab/generate_load.py
Steps to reproduce
- Run icehouse to juno or grizzly to juno jobs
Actual result
- test_migrate_glance_image_belongs_to_deleted_tenant test is failing:
```
Image image6 is not in DST image list: [u'cirros_image_for_tenant4',
u'restored image 1a58733b-5515-49cf-9e0e-8bb615c9e2a2 from host
192.168.1.3', u'restored image f60557a1-0cc0-41ca-a28e-5024a20d7a0c from
host 192.168.1.3', u'image3', u'Cirros 0.3.0 x86_64', u'image1',
u'without_checksum', u'image4', u'image2', u'cirros-0.3.3-x86_64']
```
Expected result
- All tests should succeed
=> CF-323 Fix glance image migration in jenkins

devlab/generate_load.py, devlab/tests/config.py, devlab/tests/functional_test.py, devlab/tests/testcases/test_resource_migration.py
Image will be created on src and dst with the same UUID.
After that deleted from dst before migration with the
generate_load.py script. In this case CF mustcreate new
UUID during migration for this image and migrate it successfully.
=> [CF-201] Extend functional tests to verify deleted image in dst with the same ID

docs/user/configuration.rst, docs/user/networking.rst, docs/user/networking/external_networks.rst, docs/user/networking/general_rules.rst, docs/user/networking/lbaas.rst, docs/user/networking/net_and_subnet_migration.rst, docs/user/networking/overview.rst, docs/user/networking/ports.rst, docs/user/networking/routers.rst, docs/user/networking/security_groups.rst, docs/user/user_doc_index.rst
Documents how neutron networking objects are migrated:
- Networks
- Subnets
- Floating IPs
- Security groups
- Ports
- Routers
=> CF-317 Networking migration documentation

devlab/generate_load.py, devlab/tests/config.py, devlab/tests/testcases/test_resource_migration.py
Scenario:
1. Get nova quota parameters from src cloud
2. Get neutron quota parameters from src cloud
3. Get cinder quota parameters, common for src and dst clouds
4. Get nova, neutron and cinder quotas values for each tenant from
src cloud
5. Get nova, neutron and cinder quotas values for each tenant from
dst cloud
6. Verify nova tenant quotas the same on dst and src clouds
7. Verify neutron tenant quotas the same on dst and src clouds
8. Verify cinder tenant quotas the same on dst and src clouds
=> [FT] CF-311 Validate cinder quotas migration

cloudferrylib/os/compute/nova_compute.py, cloudferrylib/utils/utils.py
When instance is created in cloud with config_drive = True option in nova.conf, VM instances don't automatically get config_drive parameter set to True on creation. This means that when migrating VMs we need to check if drive.config is attached to instance in order to find out which config_drive value to set on instance creation.
=> Migrate config_drive instance parameter.

cloudferrylib/base/action/action.py, cloudferrylib/os/actions/check_config_quota_neutron.py, cloudferrylib/os/actions/filter_similar_vms_from_dst.py, cloudferrylib/os/actions/transport_compute_resources.py, cloudferrylib/os/compute/nova_compute.py, cloudferrylib/os/identity/keystone.py, scenario/migrate_vms.yaml, scenario/stages/4_transport_compute_resources.yaml, scenario/stages_without_rollback/4_transport_compute_resources.yaml, scenario/stages_without_rollback/migrate_vms.yaml
Rename `get_tenants_list` to `_get_required_tenants_list` and use it
only for `read_info` method of `KeystoneIdentity` resource. This method
should be called only for Identity resources migration. For other cases
simple `get_tenants_list` method was created.
Get rid of Identity's `read_info` method calls in the whole project
(mostly from actions) and use `get_tenants_list` method instead.
Add tenants and users mapping obtaining method to base action class. It
allows to use it in inheritor classes and also to get rid of
`identity_transporter` action before migrating Compute resources and VMs
(calculate mapping instead of using Identity's transportation results).
Thereby identity transporter is no longer a dependency for any other
action.
Refactor related scenarios.
=> [CF-276] Optimize `get_tenants_list`

cloudferrylib/os/actions/check_filter.py, cloudferrylib/os/image/filters.py, cloudferrylib/utils/filters.py, configs/filter.yaml, docs/user/configuration.rst, tests/cloudferrylib/os/actions/test_check_filter.py, tests/cloudferrylib/os/image/test_image_filters.py, tests/cloudferrylib/utils/test_filters.py
Add a new option in the section 'image' in the filter config file - exclude_images_list. This option allow to specify images list that will be excluded during the migration process. All other images will be migrated.
If the 'images_list' and 'exclude_images_list' were specified exception will be raised. It means that in the filter config file must exists only one option - 'images_list' or 'exclude_images_list'.
=> [CF-270] Create black list feature for images in filter file

devlab/tests/config.py, devlab/tests/testcases/test_resource_migration.py
Scenario:
1. Get deleted and broken image's ids from src
2. Get all images from dst
3. Verify each deleted and broken image has been restored once
=> [FT] CF-171 Validate deleted images are restored only once

cloudferrylib/os/network/neutron.py, tests/cloudferrylib/os/network/test_neutron.py
Add `dns_nameservers` parameter to Neutron subnets entity.
=> [CF-5] Migrate DNS name servers

cloudferrylib/os/storage/plugins/iscsi/iscsi.py
Fixes cleanup process for EMC VMAX cinder backend. The problem occurred
when CF is run as non-root user, which resulted in insufficient
privileges when trying to write to a system file.
=> CF-370 EMC VMAX cleanup for non-root users

scenario/cold_migrate_autorollback.yaml, scenario/live_migrate.yaml, scenario/migrate_resources.yaml, scenario/migrate_resources_autorollback.yaml, scenario/stages_without_rollback/6_migrate_volumes.yaml
Cinder quota migration was not present in many scenarios requiring it.
=> CF-379 Add cinder quota migration to all related scenarios

cloudferry_devlab/cloudferry_devlab/tests/base.py
Raise RuntimeError exception when VM becoming in error state, do not wait until temeout will be expired.
=> [CF-352] Abort generate_load.py when vm spawned in ERROR state

cloudferrylib/os/actions/check_networks.py, cloudferrylib/os/network/neutron.py, tests/cloudferrylib/os/actions/test_check_networks.py, tests/cloudferrylib/os/network/test_neutron.py
Change the way of networks comparison. Collect all subnets hashes of
each network and use it for more accurate networks comparison
(identify which network on DST matches with the same network from SRC).
=> [CF-249] Fix floating IPs migration

cloudferry_devlab/cloudferry_devlab/generate_load.py, cloudferry_devlab/cloudferry_devlab/tests/config.py, cloudferry_devlab/cloudferry_devlab/tests/testcases/test_verify_dst_functionality.py
Fixed external network selection logic in test setUP method.
Fixed jenkins fails to boot VM or to attach cinder volume to VM.
Fixed issues in tests:
- {{VerifyDstCloudFunctionality.test_cinder_volume}}
- {{VerifyDstCloudFunctionality.test_create_vm}}
=> CF-380, 338 Post migration tests fail being unable to connect to VM.

cloudferry_devlab/cloudferry_devlab/tests/functional_test.py, cloudferry_devlab/cloudferry_devlab/tests/testcases/test_resource_migration.py, cloudferry_devlab/cloudferry_devlab/tests/testcases/test_vm_migration.py, cloudferry_devlab/cloudferry_devlab/tests/utils.py
Fix the `tenant_exists()` method in the `FunctionalTest` class.
Before this changes the method every time returns `False`,
because it called the wrong method of keystone client.
Because of this some tests in the `VmMigration` class were skipped.
Fix filtering process for vms according migration rules.
=> Fix and optimize functional tests

README.md, cfglib.py, cloudferrylib/os/actions/check_filter.py, cloudferrylib/os/actions/get_filter.py, configs/config.ini, scenario/README.md, tests/cloudferrylib/os/actions/test_check_filter.py
Remove default functionality of migrating whole cloud, if filter is
absent or empty. If the filter file is empty or if the filter file can
not be found or read, CloudFerry will raise an exception, unless there
is an option in the migrate section of CF config file to the effect of
`migrate_whole_cloud = True`.
Make `CheckFilter` return all invalid values (IDs of tenants, volumes,
VMs or images) in the filter config file instead of simple fail on the
first one.
=> [CF-357] Migrate resources with filter by default

cloudferrylib/config.py, cloudferrylib/os/discovery/cinder.py, cloudferrylib/os/discovery/glance.py, cloudferrylib/os/discovery/keystone.py, cloudferrylib/os/discovery/model.py, cloudferrylib/os/discovery/nova.py, cloudferrylib/os/discovery/stages.py, cloudferrylib/stage.py, cloudferrylib/utils/local_db.py, fabfile.py, tests/cloudferrylib/os/discovery/test_model.py, tests/cloudferrylib/test_stage.py, tests/cloudferrylib/utils/test_query.py
1) Add ability to store objects of several types to Reference(many=True)
fields.
2) Add ``links`` attribute to base schema which will hold links to objects
that are copies of original object.
3) Modify Reference deserialize code to not include references to objects
that are not exist in database. We don't want to remove any links from
DB, but we don't want stale links to be visible to our code.
4) Slightly refactor stages framework to store config as attribute instead
of passing it as argument.
5) Implement matching objects from different clouds.
=> [CF-383] Add stage for matching objects in clouds

configs/logging_config.yaml
Removed CloudFerry log Rotating by setting maxBytes parametre to 0.
BackupCount parametre has been kept as originally equal to 20.
As per Loggin handlers description: "if either of maxBytes
or backupCount is zero, rollover never occurs".
=> [CF-397] Remove CloudFerry log Rotating

cloudferrylib/os/compute/nova_compute.py
Nova boot fails with HTTP 400 Bad Request error on the server side,
which leads to failures in creating VM. The error appears randomly
and is caused by unstable Openstack environment, thus the fix would
simply retry `[migrate] retry` number of times.
=> CF-388 HTTP 400 Bad Request on nova boot

cloudferrylib/os/actions/instance_floatingip_actions.py, cloudferrylib/os/actions/prepare_networks.py, cloudferrylib/os/actions/transport_instance.py, cloudferrylib/os/compute/nova_compute.py, cloudferrylib/os/network/network_utils.py, tests/cloudferrylib/os/actions/test_transport_instance.py, tests/cloudferrylib/os/compute/test_nova.py
Fix an issue when we trying boot VM in the same availability zone,
but on another host. For example we have this case when the VM failed
during deployment on the first host. Before this patch we had exception
"Port is still in use", because port is still attached to the failed VM.
With this patch CloudFerry recreate ports for the VM and trying boot it
on another host.
=> [CF-120] Fix "Port is still in use" when attempt boot VM second time

cloudferrylib/os/compute/instances.py, cloudferrylib/os/compute/nova_compute.py
In case there is more than one flavors with the same ID in source
cloud one of which was deleted previously, migration fails to migrate
flavor which is required for the VM to boot. This patch resolves the
issue by retrieving flavor details from DB in case APIs return
reference to deleted flavor.
=> CF-384 Flavor access list for deleted flavors

cloudferry_devlab/cloudferry_devlab/generate_load.py, cloudferry_devlab/cloudferry_devlab/tests/config.py, cloudferry_devlab/cloudferry_devlab/tests/functional_test.py, cloudferry_devlab/cloudferry_devlab/tests/testcases/test_resource_migration.py, cloudferry_devlab/cloudferry_devlab/tests/testcases/test_vm_migration.py
Added in generate_load creating similar VMs on dst ans src clouds.
1. Totally same VM. VM must be treated as migrated/existing
2. VM with different flavor and image. VM must be treated as
migrated/existing.
3. VM in the different networks. VM must be treated as unrelated,
meaning that migration tool should bring up another instance
in correct network.
Next parameters added to check:
- security_groups
- metadata
=> CF-52 Extended tests for VM migration

cloudferry/fabfile.py, cloudferry/lib/os/discovery/cinder.py, cloudferry/lib/os/discovery/stages.py, cloudferry/lib/stage.py, tests/lib/os/actions/test_transport_instance.py
Move test_transport_instances module to the correct folder.
Rename all cloudferrylib references to cloudferry.lib.
=> [CF-4] Fix cloudferrylib references

cloudferry/lib/os/actions/check_networks.py, tests/lib/os/actions/test_check_networks.py
Remove private networks' overlapping check from `CheckNetworks` action,
because of it's irrelevance.
Due to https://github.com/MirantisWorkloadMobility/CloudFerry/pull/891
there is no any chance to happen such overlap, because from that moment
we started comparing networks along with their subnets before migration.
Therefore subnets overlapping within the one private network is
impossible.
=> [CF-378] Delete obsolete networks' check

cloudferry/lib/os/actions/check_networks.py
Add external networks mapping check to existing checks in the
`CheckNetwork` action. It allows us to have some overlaps, if checking
network's ID is specified in the external network mapping configuration
file (`[migrate] ext_net_map` config option contains path to this file).
In this case network will be matched with another network in the
destination cloud without creating a new one and migration will not fail.
=> [CF-378] Add `ext_net_map` check to `check_networks`

cloudferry/lib/os/discovery/nova.py, cloudferry/lib/os/migrate/glance.py, cloudferry/lib/utils/local_db.py, cloudferry/lib/utils/taskflow_utils.py
Glance use some sort of backend for storing images. It can be
Swift/Ceph/filesystem. Image file can be deleted from this backend
through SSH for filesystem backend, or through Swift API for Swift
backend or through Librados for Ceph backend. Glance will not that
image was deleted and will consider the image as active, but will
raise 404 error when you will try to download image file.
This patch handle such situation, falling back to restoring image
from compute nodes.
=> [CF-433] Handle image deleted from glance backend.

cloudferry/lib/os/image/glance_image.py
Patch fixes bug triggered by incorrect detection of existing image
when it was deleted (it was considered as active image that could be
used to boot servers).
=> [CF-442] Fix absent image detection when it was deleted previously

cloudferry_devlab/cloudferry_devlab/generate_load.py, cloudferry_devlab/cloudferry_devlab/tests/config.py, cloudferry_devlab/cloudferry_devlab/tests/testcases/test_resource_migration.py
Added dhcp_enable parameter to admin's and non-admin's subnets.
Added dhcp_enable parameter validation.
=> CF-459 Verify subnet's DHCP option is preserved during migration

cloudferry/lib/os/compute/nova_compute.py
NovaCompute.reset_state don't make additional attempts on recieving
unexpected errors (like HTTP 503) which results in failure to clean
up VMs which errored or timed out in the end of migration. This
patch fixes that.
=> [CF-401] Fix reset_state not makeing several attempts

cloudferry/cli/base.py, cloudferry/cli/v2/commands.py, cloudferry/config.py, cloudferry/discover.py, cloudferry/lib/os/discovery/cinder.py, cloudferry/lib/os/discovery/glance.py, cloudferry/lib/os/discovery/keystone.py, cloudferry/lib/os/discovery/nova.py, cloudferry/lib/os/discovery/stages.py, cloudferry/lib/os/estimation/procedures.py, cloudferry/lib/os/migrate/base.py, cloudferry/lib/os/migrate/glance.py, cloudferry/lib/os/migrate/keystone.py, cloudferry/lib/utils/query.py, cloudferry/lib/utils/taskflow_utils.py, cloudferry/model/__init__.py, cloudferry/model/compute.py, cloudferry/model/identity.py, cloudferry/model/image.py, cloudferry/model/storage.py, tests/lib/utils/test_query.py, tests/model/test_model.py
This patch decompose old discovery model into two separate entitis. One
is model which is responsible for model serialization, deserialization,
validation and storing this data into database. Other part is only
responsible for discovery. I hope this simplifies the code, make data
conversion from representation returned by OpenStack clients to
our internal representation explicit (no more magic) and makes discovery
process extensible.
=> [CF-450] Refactor discovery/model.py

cloudferry/cli/v1/commands.py, cloudferry_devlab/README.md, cloudferry_devlab/cloudferry_devlab/tests/functional_test.py
It allows to override migrate.filter_path, migrate.scenario and migrate.copy_backend options.
=> [CF-473] Add filter-path, scenario and copy-backend options to migrate command

cloudferry/lib/os/actions/task_transfer.py
If VM does not have `disk.local` file for some reason, migration
process will fail with unexpected error. This patch handles cases
when `disk.local` file is not available and logs warning message
without disrupting migration process.
=> CF-476 Failure to copy disk.local

cloudferry_devlab/cloudferry_devlab/tests/testcases/test_resource_migration.py
Fixed the VM config_drive parameter validation logic. e.g. When enabled, this parameter is set to u'1' on grizzly and u'True' on juno.
=> [CF-477] Incorrect validation of config_drive param in functional tests

cloudferry_devlab/cloudferry_devlab/generate_load.py, cloudferry_devlab/cloudferry_devlab/tests/base.py, cloudferry_devlab/cloudferry_devlab/tests/config.py, cloudferry_devlab/cloudferry_devlab/tests/testcases/test_resource_migration.py, cloudferry_devlab/cloudferry_devlab/tests/testcases/test_verify_dst_functionality.py, cloudferry_devlab/cloudferry_devlab/tests/testcases/test_vm_migration.py
Preparing src_dst_vms list by matching the vms by vm_hash.
Add additional information to the message on failure.
Add calling a wait_until function for emulate_vm_states.
Rename wait_until_objects_created function to wait_until_objects.
=> [CF-479] Match VMs by vm_hash instead of name

cloudferry/lib/os/actions/check_vmax_prerequisites.py, cloudferry/lib/os/storage/plugins/iscsi/iscsi.py, cloudferry/lib/utils/local.py
`local_sudo_password` config option used to introduce a lot of
mistakes into config file because it was unclear whether it's needed
or not and often migration failed with cryptic errors during ISCSI
discovery. This patch adds verification which suggests to set
`local_sudo_password` if it's not set and adds better error handling
for local command execution to avoid cryptic errors.
=> CF-472 local_sudo_password pre-check

cloudferry_devlab/cloudferry_devlab/tests/config.py
Configured the tn5server3 VM for DST Cloud to an IP Address not used by DHCP interface for subnet 122.2.2.0/24 created on DST Cloud.
=> [CF-474] error during VM provisioning in destination cloud with generate_load.py

cloudferry_devlab/cloudferry_devlab/tests/testcases/test_vm_migration.py
Functional tests were failing because a VM, that was marked in ERROR state on source cloud as part of generate load, was not migrated and functional tests were trying to validate its params on destination cloud which was incorrect.
=> [CF-480] VMs parameter validation functional test fails after icehouse to juno migration

cloudferry/cfglib.py, cloudferry/lib/os/compute/nova_compute.py, cloudferry/lib/os/image/glance_image.py, cloudferry/lib/os/network/neutron.py, cloudferry/lib/os/object_storage/swift_storage.py, cloudferry/lib/os/storage/cinder_storage.py, tests/lib/os/compute/test_nova.py, tests/lib/os/image/test_glance_image.py, tests/lib/os/network/test_neutron.py, tests/lib/os/storage/test_cinder_storage.py
In some cases `publicURL` used as nova endpoint type by default in nova
client returns empty list of services. This patch allows specifying nova
endpoint type for nova client to resolve these issues.
=> CF-503 Allow providing nova endpoint type

cloudferry_devlab/cloudferry_devlab/tests/functional_test.py, cloudferry_devlab/cloudferry_devlab/tests/testcases/test_glance_image_migration.py
Added migrate2 tag to tests.
Fixed image list requesting without public ones.
Fixed missed description for a test.
=> CF-451 Fix image migration functional tests to work with migrate2

cloudferry_devlab/Vagrantfile, cloudferry_devlab/provision/configure_openstack.sh
This patch allows to run VMs from boxes that were created from VMs
against which generate_load.py was executed.
Commands to run both SRC, DST and NFS VMs:
$ vagrant up /icehouse_juno_.*/
$ vagrant up /grizzly_juno_.*/
=> [CF-512] Add generate_load.py-ed boxes to Vagrantfile

cloudferry/actions/helper/task_transfer.py, cloudferry/lib/copy_engines/base.py, cloudferry/lib/copy_engines/bbcp_copier.py, cloudferry/lib/copy_engines/rsync_copier.py, cloudferry/lib/os/storage/plugins/copy_mechanisms.py, cloudferry/lib/utils/files.py, tests/lib/copy_engines/test_base.py
When volumes or ephemerals are copied between compute nodes in source
and destination with non-root user, there might be no write
permissions in the destination folder, which leads to copy failures.
This patch resolves the issue by temporarily adding 777 permissions
for a folder in destination and reverting it back once copy is done.
=> CF-519 Missing write permissions in destination for file copy

cloudferry/lib/os/compute/nova_compute.py, tests/lib/os/compute/test_nova.py
Because proxy client wasn't used in NovaCompute.change_status it
didn't retry request on failure. This could fail migration because
of HTTP 413 "Request was rate limited" error. This patch make this
method to use proxy client.
=> [CF-528] Use proxy client in NovaCompute.change_status

cloudferry/lib/utils/remote_runner.py, tests/lib/copy_engines/test_bbcp_copier.py, tests/lib/utils/test_runner.py
Unittests previously spawned ssh-agent on each run which resulted in
hundreds of ssh-agent processes on CI nodes.
=> CF-524 Unit tests don't spawn ssh-agent anymore

cloudferry/actions/prechecks/check_networks.py, cloudferry/cloud/grouping.py, cloudferry/lib/os/compute/nova_compute.py, tests/lib/os/actions/test_check_networks.py
ComputeInfo class correctly passes search_opts parameters to get_instances_list function.
get_instances_list function of NovaCompute returns list of servers according to the filters,
also it supports several tenants in filters.
=> [CF-493] Fix checking that VMs spawned in external networks

cloudferry_devlab/cloudferry_devlab/generate_load.py, cloudferry_devlab/cloudferry_devlab/tests/base.py, cloudferry_devlab/cloudferry_devlab/tests/config.py, cloudferry_devlab/cloudferry_devlab/tests/functional_test.py, cloudferry_devlab/cloudferry_devlab/tests/images.py, cloudferry_devlab/cloudferry_devlab/tests/testcases/test_glance_image_migration.py
1) Below scenario added to functional tests (CF-362)
- Create image
- Add image to filter file as black listed
- Run image migration
- Make sure all images except for black-listed migrated successfully
2) Fixed the issue that last set of Functional Tests referring filter file of last migrated tenant for resource validation (CF-456)
=> [CF-362,456] Extend functional tests to include verification of blacklisted images

cloudferry_devlab/cloudferry_devlab/generate_load.py, cloudferry_devlab/cloudferry_devlab/tests/config.py, cloudferry_devlab/cloudferry_devlab/tests/functional_test.py, cloudferry_devlab/cloudferry_devlab/tests/testcases/test_vm_migration.py
Scenario added -
1. Create flavor with some specific ID in source cloud with some attributes.
2. Delete that flavor
3. Create flavor with the same ID, but with different attributes
4. Boot VM from 'deletedflavor' flavor
5. Run migration for VM
6. Verify VM migrated successfully to destination and is booted from correct flavor
=> [CF-394] Extend functional tests to verify migration of deleted flavors

cloudferry_devlab/cloudferry_devlab/tests/testcases/test_vm_migration.py
For the VMs created in ERROR state on source cloud, Fixed Functional Tests to not verify flavor ID for those VMs after migration as these VMs are not migrated.
=> [CF-543] Functional Tests should not verify flavor ID for VMs not migrated

cloudferry_devlab/provision/configure_openstack.sh
All boxes except grizzly have API rate limit disabled. This patch
configures nova on all boxes to disable API rate limit.
=> CF-550 Disable API rate limit for grizzly box

cloudferry/actions/prechecks/check_networks.py, cloudferry/cfglib.py, cloudferry/lib/base/action/action.py, cloudferry/lib/os/compute/nova_compute.py, cloudferry/lib/os/compute/server_groups.py, cloudferry/lib/os/identity/keystone.py, cloudferry/lib/os/image/glance_image.py, cloudferry/lib/os/network/neutron.py, cloudferry/lib/os/storage/cinder_storage.py, cloudferry/lib/utils/mapper.py, configs/ext_net_map.yaml, configs/resource_map.yaml, tests/lib/os/network/test_neutron.py
This patch adds ability to map some tenant name on source to
some tenant name on destination meaning that CloudFerry will
assume that mapped tenant on source is the same as tenant on
destination even though they have different names.
=> [CF-545] Add ability to map different tenant names in src and dst

cloudferry_devlab/cloudferry_devlab/generate_load.py
VMs are started, resized, etc in restore_vm_states script anyway. So
keeping them active is a waste of CPU and RAM resources. This patch
will make sure that there is only one VM active during generate_load
=> Modify generate_load script to shut off all VMs

cloudferry_devlab/cloudferry_devlab/generate_load.py
Looks like boxes built with last patch which shut off VMs immediately
don't pass test because their volumes and ephemeral disks don't have
any changes made by generate_load. This should be fixed by flushing
VM disk caches.
=> Flush VM caches before shutting off

cloudferry/lib/copy_engines/scp_copier.py, cloudferry/lib/utils/files.py
SCP copying failed because temporary directory created by SCP engine
didn't have enough permissions when migration is run with non-root user.
Resolved by temporarily adding full permissions to temporary path.
=> CF-554 SCP not having enough permissions to copy to destination

cloudferry/lib/os/storage/plugins/nfs/generic.py
Volume migration failed for non-root user because it was unable to
find volume object on NFS share. This patch resolves the problem by
running `find` command with elevated privileges.
=> CF-560 Volume migration for non-root user

cloudferry/lib/os/discovery/nova.py
Discover is not working in cloud where there is volume attachment
to deleted volume. Although we couldn't reproduce this error without
modifying the database, the error occured on production. This patch
fix the issue.
=> [CF-505] Fix error when attachment exists but volume deleted

cloudferry/lib/os/estimation/procedures.py
Use Attachment.volume instead of Attachment.
=> [CF-552] Attachment object has no 'size' attribute

cloudferry/actions/compute/transport_ephemeral.py
VM migration fails if backing file for the ephemeral drive is somehow
missing in source cloud. The patch resolves this problem by ignoring
missing backing file and only copying the base ephemeral.
=> CF-574 VM migration when backing file is not present

cloudferry/actions/block_storage/migrate_volumes.py, cloudferry/lib/os/compute/nova_compute.py, cloudferry/lib/os/storage/cinder_storage.py, cloudferry/lib/utils/override.py, configs/config.ini, configs/override_rules.yaml, tests/lib/os/storage/test_cinder_storage.py, tests/lib/utils/test_override.py
Adds support to migrate cinder volumes to non-default cinder backends.
This resolves cinder migration issues when source cloud has NFS backend
but destination cloud has NFS and non-NFS backend, and non-NFS backend
is configured as default.
=> CF-572 Migrate volumes to non-default backends

cloudferry_devlab/cloudferry_devlab/generate_load.py, cloudferry_devlab/cloudferry_devlab/tests/base.py, cloudferry_devlab/cloudferry_devlab/tests/config.py, cloudferry_devlab/cloudferry_devlab/tests/testcases/test_glance_image_migration.py, cloudferry_devlab/cloudferry_devlab/tests/testcases/test_keystone_migration.py, cloudferry_devlab/cloudferry_devlab/tests/testcases/test_networking_migration.py, cloudferry_devlab/cloudferry_devlab/tests/testcases/test_nova_resource_migration.py, cloudferry_devlab/cloudferry_devlab/tests/testcases/test_verify_dst_del_tenant_resources.py, cloudferry_devlab/cloudferry_devlab/tests/testcases/test_verify_dst_functionality.py, cloudferry_devlab/cloudferry_devlab/tests/testcases/test_verify_dst_net_segm_id.py, cloudferry_devlab/cloudferry_devlab/tests/utils.py
Added the below scenario:
-     Create tenant "tenant2" in source cloud
-     Map "tenant2" to "tenant-2" in configs/resource_map.yaml mapping file
-     Create image, network, VM with attached volume in "tenant2" tenant
-     Run migration
-     Verify all created objects successfully migrated to destination tenant "tenant-2"
=> [CF-551] Extend functional tests to verify tenant mapping functionality

cloudferry/lib/copy_engines/bbcp_copier.py, tests/lib/copy_engines/test_bbcp_copier.py
If migration is done with bbcp as copy engine, bbcp is being copied to
both source and destination nodes prior to ephemeral migration, but if
bbcp was previously copied to the node from different user, current
user may not have permissions to overwrite existing bbcp executable and
migration would fail. This patch resolves this issue by reusing existing
bbcp and assigning 777 permissions to the file so that it can be
overwritten by anyone.
=> CF-591 Check if bbcp is installed and allowed to be owerwritten

cloudferry_devlab/cloudferry_devlab/generate_load.py, cloudferry_devlab/cloudferry_devlab/tests/base.py, cloudferry_devlab/cloudferry_devlab/tests/cleanup.py, cloudferry_devlab/cloudferry_devlab/tests/config.py, cloudferry_devlab/cloudferry_devlab/tests/mysql_connector.py, cloudferry_devlab/cloudferry_devlab/tests/testcases/test_cinder_migration.py
Below scenario is automated:
- Create a VM on the source cloud.
- Create a volume on the source cloud and attach to the above VM.
- Delete the above volume from the database.
- Run migration. Verify that the VM migrated successfully to the destination cloud without the above volume attached.
=> [CF-542] Extend functional tests to verify migration of VM with attached deleted volume

cloudferry_devlab/cloudferry_devlab/generate_load.py, cloudferry_devlab/cloudferry_devlab/tests/config.py, cloudferry_devlab/cloudferry_devlab/tests/testcases/test_nova_resource_migration.py
Below is the test case for Icehouse to Juno migration (Grizzly does not support user quotas)
-     Set `[migrate] migrate_user_quotas = True` in config
-     Create user user_with_quotas in source cloud
-     Add custom user quotas to user_with_quotas user
-     Run migration with 4_transport_compute_resources.yaml scenario
-     Verify user quotas appear in destination cloud
=> [CF-603] Extend functional tests to verify migration of user quota migration

cloudferry/lib/migration/notifiers.py, cloudferry/lib/os/identity/keystone.py
Tenant migration resulted in full tenant object being printed in
"Destination ID" field, instead of tenant ID only, which was caused
by incorrect data being passed to notification observer.
=> CF-641 Invalid report for tenant migration

cloudferry/lib/copy_engines/bbcp_copier.py, tests/lib/copy_engines/test_bbcp_copier.py
bbcp must always be copied to /tmp/bbcp on remote hosts and executed there
=> CF-644 Make sure bbcp is installed on remote hosts in /tmp/bbcp

cloudferry/lib/utils/mapper.py
When user specifies mapping in `[migrate] resource_map` file to nothing,
`AttributeError` is risen, for example:
```
$ cat configs/resource_map.yaml
tenant_map:
```
This patch would raise configuration error in that cases stating that
one cannot assign mapping to nothing.
=> CF-652 Mapping to nothing raises AttributeError

cloudferry_devlab/requirements.txt, cloudferry_devlab/setup.py
restore_vms_state script fails with ImportError:
```
$ restore_vms_state
Traceback (most recent call last):
File
"CloudFerry/cloudferry_devlab/.venv/bin/restore_vms_state",
line 9, in <module>
load_entry_point(Userscloudferry-devlab==0.0.0', 'console_scripts',
Usersrestore_vms_state')()
File
"CloudFerry/cloudferry_devlab/.venv/lib/python2.7/site-packages/pkg_resources/__init__.py",
line 558, in load_entry_point
return get_distribution(dist).load_entry_point(group, name)
File
"CloudFerry/cloudferry_devlab/.venv/lib/python2.7/site-packages/pkg_resources/__init__.py",
line 2682, in load_entry_point
return ep.load()
File
"CloudFerry/cloudferry_devlab/.venv/lib/python2.7/site-packages/pkg_resources/__init__.py",
line 2355, in load
return self.resolve()
File …
```
=> CF-657 restore_vms_state fails with ImportError

cloudferry/lib/os/network/neutron.py, tests/lib/os/network/test_convert_sg.py
In some scenarios security group rules in source and destination may
differ by string representation of remote_ip_prefix field, for example
'1.2.3.4' in source cloud, and '1.2.3.4/32' in destination cloud.
Even though those networks/IPs are the same, CF would interpret those
as different and abort with exception during security group migration.
=> CF-659 Security groups with and without bitmask

cloudferry/lib/os/image/glance_image.py
Some images may raise CommunicationError during download:
```
CommunicationError: Error finding address for
https://some.openstack.deployment.com/v1/images/4c5d0874-933d-4eef-859e-697d44d51bd1
```
This exception was not handled properly and resulted in VM migration
failures. This patch resolves the issue by correclty handling this
exception.
=> CF-661 Invalid glance image URL breaks VM migration
