cloud/os2os.py, cloudferrylib/utils/drivers/ssh_ceph_to_ceph.py, cloudferrylib/utils/rbd_util.py, configs/filter.yaml
Import - Export full data between ceph clusters was changed to diff import - export
=> rbd volumes diff transferring in ceph-ceph case

cloudferrylib/os/actions/deploy_snapshots.py, cloudferrylib/os/network/neutron.py
=> Fix driver in deploy_snapshots. Fix uploading sec_gr rules in services tenant

requirements.txt
=> Little fix for requirements.

.gitignore, requirements.txt
- added ecdsa to pip req.txt
- added pycrypto to pip req.txt
- added *.sw* to .gitignore for vim compatibility
=> fixed minor dependencies problems

dry_run/chain.py, dry_run/tasks/simple.py, fabfile.py
- added "dry_run" task in CloudFerry that runs stub tasks
- created stub tasks
=> implement SAIC-50: Add support for dry running CF

cloud/os2os.py, cloudferrylib/os/actions/copy_object2object.py, cloudferrylib/os/actions/fake_action.py
Added tasks related to available resources migration, like volumes in available state migraiton, object storage migration.
=> Cold data migration task, fixed objects migration

cloudferrylib/scheduler/scheduler.py, cloudferrylib/utils/utils.py, configs/logging_config.yaml, fabfile.py, requirements.txt
- all logging configs moved to configs/logging_config.yml
- added logging exception in scheduler
- with call migrate:debug=True logger shows debug messages
- added stream output with error log level to error.log
- added stream output with info level to info.log
=> implement SAIC-40 : Add logging to scheduler in CF

cfglib.py, cloud/cloud.py, cloudferrylib/os/actions/snapshots.py, configs/config.ini
- added task that makes dumps of mysql and copies them to remote host
- added task that applies mysqldump to existing database
- extended config.ini with [snapshot] section where settings are
stored
=> Implement SAIC-36 : snapshots support of CF

.gitignore, devlab/README.md, devlab/Vagrantfile, devlab/provision/cloudferry.sh, devlab/provision/keys.sh, devlab/provision/prerequisites.sh, devlab/provision/user.sh
This allows easily set up development environment using vagrant.
=> SAIC-8 Development environment

cloud/os2os.py, cloudferrylib/scheduler/scenario.py, cloudferrylib/scheduler/scheduler.py, scenario/migrate.yaml, scenario/tasks.yaml
- added multichain scheduler support
- extended scenario file with additional chains
=> Implement SAIC-23 : add rollbacks to CF scheduler

cloudferrylib/os/compute/nova_compute.py
...in the Cloudferry nova_compute resource.
=> SAIC-71: Fix bug with the old 'get_client' method

.gitignore, devlab/README.md, devlab/Vagrantfile
- Fixes invalid neutron configuration on icehouse VM
- Moves all boxes to shared account, not tied to any personal account
=> SAIC-73. Fix icehouse and grizzly dev env

cloudferrylib/os/compute/nova_compute.py, configs/config.ini
Fix in nova_compute.
Also add placeholders in config file for RabbitMQ
=> [SAIC-91] Check ssh task don't work on Grizzly

cloud/cloud.py
- doesn't use swift resource in case objstorage resource is not
specified
=> Implements SAIC-66: make swift usage configurable

configs/config.ini
Lead to an overall view of the configs/config.ini.
=> Minor fix: Config refactoring

devlab/provision/cloudferry.sh
* There's a need to standardize tooling we use for static analysis. To
simplify static analysis, all the correct tools should be added
to the devenv's virtualenv.
* SAIC-14 feature requires Redis server to be run, thus it needs to be
added to devenv.
=> SAIC-104 Extend devenv with redis and static analysis tools

cloudferrylib/os/compute/nova_compute.py
Added checking for type of flavor (public/private). In case of private flavors added working with permissions (allowed tenants for flavor).
=> Private flavors

devlab/README.md, devlab/Vagrantfile, devlab/config.ini, devlab/config.template, devlab/provision/cloudferry.sh
Added sample.ini config for cloudferry development lab.
Added description with how to run migration process from cloudferry vm.
Made changes in cloudferry provisioning: added sample.ini copying.
=> SAIC-102: Optimize vagrant devlab preparations

cfglib.py, cloud/cloud.py, cloud/os2os.py, cloudferrylib/os/actions/check_bandwidth.py, cloudferrylib/utils/cmd_cfg.py, cloudferrylib/utils/utils.py, configs/config.ini, scenario/migrate.yaml, scenario/tasks.yaml
- Add 'check_bandwidth' action;
- Add 'initial_check' section to config;
- Add 'timer' function to cloudferrylib/utils/utils.py to measure python
functions execution time.
=> SAIC-17: Check bandwidth

cfglib.py, condensation/__init__.py, condensation/action.py, condensation/algorithms.py, condensation/cloud.py, condensation/flavor.py, condensation/group.py, condensation/node.py, condensation/process.py, condensation/scripts/hardware_collector.py, condensation/scripts/nova_collector.py, condensation/utils.py, condensation/vm.py, configs/config.ini, data_storage.py, fabfile.py, requirements.txt, tests/condensation/test_action.py, tests/condensation/test_cloud.py, tests/condensation/test_flavor.py, tests/condensation/test_group.py, tests/condensation/test_node.py, tests/condensation/vm.py
- takes group, hardware, nova files as input
- produces db entries as output
=> SAIC-14 : Schedule tasks for limited dst capacity

devlab/tests/README.md, devlab/tests/config.py, devlab/tests/prerequisite_actions.py
Added generator and config file to generate load on "src" node in 
devlab-environment.
Added description about usage and configuration.
=> SAIC-113 Test load generator implementation

devlab/utils/repackage_box.sh
1. Improved help message;
2. Fixed packaging naming.
=> Minor improvements to box packaging script

cfglib.py, cloudferrylib/os/actions/snapshots.py, configs/config.ini
- changed copying function to fabric.local + scp
=> Implements SAIC-100 : mysqldump fix

cloudferrylib/os/actions/check_needed_compute_resources.py
When a flavor is updated, the flavor id will
change. If an instance is in this flavor,
it will keep the old flavor id, can not be
matched to existing flavors
If detected, abort the migration with error
message.
modified:   cloudferrylib/os/actions/check_needed_compute_resources.py
=> SAIC-131 to detect obsolete flavor ID

cloudferrylib/os/network/neutron.py
Different versions of quantum/neutron clients raise different types of
exceptions on the same error (floating ip quota exceed). Also, they use
absolutely different error messages. From now we will handle it with
more general exception and status code check.
=> SAIC-69: Fix bug with the Floating IPs quota excess

devlab/tests/README.md, devlab/tests/config.py, devlab/tests/openrc.example, devlab/tests/prerequisite_actions.py, devlab/tests/test_resource_migration.py
Fixed prerequisites actions to use SRC and DST cloud credentials/endpoints.
Added openrc example file.
Added resource migration autotest suit.
Moved client's version constants to config.py
Added virtualenv preparation step to READ.me
Pep8 fixes.
=> SAIC-119 Nova, keystone and neutron resources migration auto tests

devlab/config.template, devlab/tests/config.py
Fixed tenants paramenters in load_generator
Added lost parameters from config.template
=> Changes in test configs due to changes in CF

devlab/config.template, devlab/tests/test_resource_migration.py
Added lost parameters for networks, vms, images.
Fixed imports for tests from load_generator.
=> Changes in configuration template and tests import

cloudferrylib/scheduler/scenario.py
From now CloudFerry filters files out before loading them as modules in
case of scenario.
=> SAIC-106: Fix bug with modules loading in scenario

devlab/utils/repackage_box.sh
- Fixes SSH key insertion;
- Improves readability;
- Adds grizzly-specific case handling;
=> Repackage script fixes

devlab/tests/config.py, devlab/tests/generate_load.py
Implement SRC cloud cleaning with pre-generated objects from config.py
=> Added generated resource cleaning option to load_generator.

devlab/tests/test_resource_migration.py, devlab/tests/test_vm_migration.py
Added key-values validations to resource_migration suite.
Created VM cold migration tests.
=> SAIC-120 VM cold-migrated successfully auto test

cloud/os2os.py, cloudferrylib/os/actions/check_instances.py, scenario/migrate.yaml, scenario/tasks.yaml
=> Fixes Bug Saic-67 : CF fails if there are no vms

devlab/config.template, devlab/tests/config.py, devlab/tests/generate_load.py
Expanded config.py with tenant's parameters.
Fixed logic in load generator.
=> SAIC-136 test load improvements.

cloudferrylib/utils/utils.py
ssh-agent now starts for the first ssh command issued and never gets
killed. This is done in order to improve end-user (deployment engineer)
experience in case he/she has password-protected private key. With this
patch enabled password is only required to be entered once for the whole
migration process.
=> SAIC-170 Start ssh-agent once for each private key

cloudferrylib/os/network/neutron.py, tests/cloudferrylib/os/network/test_neutron.py
=> Fixes SAIC-62:quantum nonetype check

cfglib.py, cloudferrylib/os/actions/get_filter.py, cloudferrylib/os/actions/get_info_images.py, cloudferrylib/os/image/glance_image.py, configs/config.ini, configs/filter.yaml, tests/cloudferrylib/os/image/test_glance_image.py
- configurable migration of images from all tenants
- added feature to filter snapshots by date
- fixed metadata migration for snapshots
- added feature to migrate image members
- fixed glance_client initialization with endpoint ending with "v2"
=> Implements SAIC-123: Glance resources migration

cloudferrylib/os/actions/prepare_networks.py
Since the creation order of DHCP port and instance port can be random,
sometimes, the DHCP port can take the IP already used by instance on the
source could. To avoid it, this fix will disable DHCP for all networks
in all tenants, participated im migration process, and free it's IP
before instance port creation, then re-enable the DHCP.
=> SAIC-156: Fix DHCP issue for all tenants

cloudferrylib/os/storage/cinder_database.py
- swapped numerator with denominator
=> Fixes SAIC-202

devlab/config.template, devlab/tests/config.py, devlab/tests/generate_load.py, devlab/tests/test_resource_migration.py
* Added volumes generating.
* Added snapshot generating.
* Snapshot attaching to vm.
* Configuration's template changes added.
* SAIC-183: Added resource validation for cinder objects.
* SAIC-206: Optimized config's parameters passing to functions.
* Fixed networking cleanup.
* Added roles generating.
* Optimized cleaning scenario output.
=> SAIC-173 Create cinder volumes from generate_load

devlab/README.md, devlab/Vagrantfile, devlab/config.ini, devlab/utils/repackage_box.sh
Added icehouse and grizzly's compute nodes to Vagrantfile.
Updated configs for devlab using computes.
Updated repackage_box with to generate new boxes.
Updeted Readme file.
=> SAIC-181: Extend devlab to have more compute node

devlab/tests/config.py, devlab/tests/generate_load.py, devlab/tests/test_resource_migration.py, devlab/tests/test_vm_migration.py
Added method to emulate vm's statuses.
Added config options.
=> SAIC-191: Load generator should generate VMs in different states.

cloudferrylib/os/storage/cinder_database.py
The issue was fixed with SAIC-222 patch, this patch adds debug
information for SQL statements executed and minor code improvements.
=> SAIC-196 NFS volume with snapshot in error state

condensation/scripts/__init__.py, condensation/scripts/nova_collector.py, fabfile.py
Knife works only with Chef deployed cloud. For more general cases we must use Nova API for get hardware information.
=> [SAIC-213] Replace current knife based hardware info collector

devlab/config.template
Updated quota migration default value.
Added 'down'-state host ignoring by default.
Decreased testing file size to check bandwidth.
Removed comments from template.
=> Optimized config template for devlab.

condensation/cloud.py, condensation/flavor.py
Condensation used to fail in case flavor was non-int value. This
patch fixes it.
=> SAIC-235 Fix condensation for flavors with non-int IDs

cfglib.py, cloudferrylib/os/network/neutron.py, configs/config.ini, configs/ext_net_map.yaml, tests/cloudferrylib/os/network/test_neutron.py
Added external networks mapping option (ext_net_map in config file).
This option allow to map external networks on source cloud to
existing external networks on destination cloud with appropriate parameters by
dictionary with old and new ids.
=> External networks mapping option

cfglib.py, cloudferrylib/os/identity/keystone.py, configs/config.ini, devlab/config.template, tests/cloudferrylib/os/identity/test_keystone.py
Patch provides possibility to enable/disable users migration in the config.
=> SAIC-205: Make users migration optional

cfglib.py, cloudferrylib/os/compute/nova_compute.py, configs/config.ini, devlab/config.template, tests/cloudferrylib/os/compute/test_nova.py
Nova quotas migration fucntionality implemented by Nova API instead
of interraction with DB.
=> SAIC-234 Nova quotas migration

cloudferrylib/os/network/neutron.py
Used wrong key for getting port_range_max parameter
=> little fix for sec groups rule uploading

devlab/README.md, devlab/Vagrantfile, devlab/config.ini, devlab/provision/cloudferry.sh, devlab/provision/generate_config.sh
- Removed dependency on cloudferry repo path from configuration - less
options to configure!
- Fixed requirements installation occured due to working directory
stayed home of root user (invalid `sudo` invocation).
=> SAIC-264 cloudferry VM devlab provisioning fix

cfglib.py, cloudferrylib/os/compute/instances.py, cloudferrylib/os/compute/nova_compute.py, condensation/action.py, condensation/process.py, configs/config.ini, devlab/config.template, evacuation/actions/evacuate_vms.py, evacuation/evacuation_chain.py, fabfile.py, tests/cloudferrylib/os/compute/test_live_migration.py
- script reads series of actions from db and performs
novaclient.servers.live_migrate call for each action
=> SAIC-180 VM evacuation

HACKING.md
Provides description on how to extend cloudferry
=> Add hacking.md

devlab/tests/config.py, devlab/tests/generate_load.py, devlab/tests/test_vm_migration.py
Added required VM statets into config.py, updated generate_load.py
script in order to generate VM in required states, updated
test_vm_migration.py to verify VM state migration.
=> VM states verification test updated.

cloud/cs2os.py, cloudferrylib/cs/client/client.py, cloudferrylib/cs/compute/compute.py, cloudferrylib/cs/identity/identity.py, cloudferrylib/os/compute/nova_compute.py, cloudferrylib/os/identity/keystone.py, scenario/migrate_cs2os.yaml, scenario/tasks_cs2os.yaml
Signed-off-by: Andrei Topilin <atopilin@mirantis.com>
=> Add identity transport for CS2OS

devlab/tests/generate_load.py
Added support for cleaning security-groups.
New argument can be used for choosing cloud.
=> Improvement in generate_load.py

cloudferrylib/utils/files.py, cloudferrylib/utils/remote_runner.py, tests/cloudferrylib/utils/__init__.py, tests/cloudferrylib/utils/test_file_utils.py, tests/cloudferrylib/utils/test_runner.py
Added classes which handle remote symlink and temporary files creation
which are created on scope enter, and destroyed on scope exit.
=> Safe remote files and symlink creation

devlab/tests/config.py, devlab/tests/generate_load.py
Added a new VM and flavor, flavor was deleted after VM spawning.
=> Migrate VM when flavor is not present.

cloudferrylib/utils/files.py, cloudferrylib/utils/remote_runner.py, tests/cloudferrylib/utils/test_runner.py
=> Extended remote runner: get temp dir

devlab/README.md, devlab/Vagrantfile, devlab/config.ini, devlab/provision/devstack/devstack.sh, devlab/provision/devstack/local_juno.conf
=> Added scripts to install juno devstack

configs/filter.yaml, devlab/tests/migrate.yaml, scenario/migrate.yaml
process. Also updated filter.yaml for it to be in correct format.
=> Modified migrate.yaml file in order to include image filtering in

HACKING.md
Added howto for contributing to HACKING.md.
=> Contributing guide updates

devlab/tests/functional_test.py, devlab/tests/test_resource_migration.py, devlab/tests/test_vm_migration.py
Removes lower-level libraries debug logging from nosetests reports
=> SAIC-339 Readable functional tests error messages

devlab/jenkins/run_functional_tests.sh
Added script to run functional tests from Jenkins job(s), please review
=> Script to run functional tests

devlab/utils/clean_run.sh, devlab/utils/deploy_lab.sh, devlab/utils/os_cli.sh
Added all-tenants support for os_cli image cleaning.
Added usage description for each script.
=> Updated scripts for cleaning lab, deploy lab and run migration

cloudferrylib/os/compute/nova_compute.py
Implement availability to migrate Nova Compute default quotas. It is
possible if `migrate_quotas` option of config's `migrate` section is
`True`.
=> [SAIC-300] Add Nova default quotas migration

cloudferrylib/scheduler/scheduler.py, cloudferrylib/scheduler/signal_handler.py, cloudferrylib/utils/utils.py
By default we catch 
> class Exception(BaseException):
Ctrl+C is KeyboardInterrupt exception. From source we can see:
> class KeyboardInterrupt(BaseException):
Let's except BaseException it will cover all needed cases.
=> [SAIC-325] Use traps to handle signals (CTRL+C) in CF

devlab/tests/groups_example.yaml, devlab/tests/test_group_verification.py
Also groups_example.yaml file was added for testing purposses.
=> Added a grouping procedure verification test case.

cloudferrylib/os/identity/keystone.py, cloudferrylib/os/network/neutron.py, tests/cloudferrylib/os/network/test_neutron.py
Adds logging information to neutron migration process
=> SAIC-302 Neutron migration logging

cloudferrylib/os/identity/keystone.py, tests/cloudferrylib/os/identity/test_keystone.py
Implements class which allows safe operations on objects which do not
belong to admin user. Currently required for VM to be booted and
floating IP to be created in non-admin tenant.
=> SAIC-356 Add admin user to non-admin tenant

devlab/tests/test_resource_migration.py
Adds functional test which verifies floating IP migration: all floating
IPs on source are the same as floating IPs on destination.
=> Floating IP migration functional test

cloudferrylib/os/image/glance_image.py
Remove information about obsolete/broken images (and snapshots) from
`info` variable, because we do not migrate them. We need to delete it,
cause this information is used during the migration process (for example
for images mapping) and can break the migration.
Also, logging has been removed from the `get_image_ref` method of
`glance_image` resource due to it's uselessness.
=> [SAIC-371] Fix issue with obsolete images

cloudferrylib/os/compute/nova_compute.py
Temporary fix for default nova quotas migration. Must be fixed in
future.
=> Default nova quotas migration fix

cloudferrylib/os/compute/nova_compute.py, tests/cloudferrylib/os/compute/test_nova.py
Simplifies and improves readability of flavor migration code
=> SAIC-386 Refactor flavor migration code

devlab/provision/generate_config.sh, devlab/tests/test_group_verification.py
=> Updated grouping test, configuration.ini is created in test repo.

cloud/os2os.py, cloudferrylib/os/actions/transport_ephemeral.py, cloudferrylib/utils/drivers/ssh_chunks.py, cloudferrylib/utils/drivers/ssh_file_to_file.py, cloudferrylib/utils/files.py, cloudferrylib/utils/remote_runner.py, cloudferrylib/utils/utils.py, devlab/tests/migrate.yaml, scenario/tasks.yaml, tests/cloudferrylib/utils/test_file_utils.py, tests/cloudferrylib/utils/test_runner.py
Refactors direct file copy logic, and adds support for passwords with special characters.
=> SAIC-402 Support for passwords with special characters

tests/cloudferrylib/os/compute/test_nova.py
Fixed incorrect unit test for non-public nova flavor migration.
=> Non-public flavor migration unit test fix

devlab/Vagrantfile, devlab/jenkins/copy_code_to_cf.sh, devlab/jenkins/functional_tests.sh, devlab/jenkins/gen_load_and_migration.sh, devlab/jenkins/nosetests.sh, devlab/jenkins/setup_lab.sh
- Add ConnectionAttempts=3 to ssh client settings
- Increase RAM to 4G for Icehouse VM
- Delete multiply "vagrant destroy --force" commands
- Add "vagrant status" for better debugging
=> Tweak jenkins scripts

devlab/Vagrantfile, devlab/jenkins/cf/generate_load.sh, devlab/jenkins/cf/run_migration.sh, devlab/jenkins/cf/run_nosetests.sh, devlab/jenkins/copy_code_to_cf.sh, devlab/jenkins/functional_tests.sh, devlab/jenkins/gen_load_and_migration.sh, devlab/jenkins/nosetests.sh, devlab/jenkins/setup_lab.sh, devlab/utils/os_cli.sh
- Add possibility to test pull request on grizzly-to-icehouse, grizzly-to-juno and icehouse-to-juno environments;
- Rename cloudferry folder to default one [SAIC-417]
=> Multi tests

cloudferrylib/os/identity/keystone.py, devlab/tests/test_resource_migration.py
Fixes migration of users which have non-existing primary tenant defined.
=> SAIC-418 Migration of users with primary tenant deleted

QUICKSTART.md, README.md
Adds quick start guide document for new engineers willing to start
playing with CloudFerry.
=> Quick start guide

devlab/tests/data_collector.py, devlab/tests/generate_load.py
Changelog:
- Fixed data_collector script, to collecect only required data.
=> Release 2015-08-30

devlab/tests/test_resource_migration.py
Verifies segmentation ID of a network migrated correctly.
=> SAIC-422 Segmentation ID migration auto tests

devlab/tests/test_resource_migration.py
With this commit functional tests compare parameters of  the same resource.
=> Changed validation of neutron resource parameter in functional tests

cloudferrylib/base/resource.py, cloudferrylib/os/actions/attach_used_volumes_via_compute.py, cloudferrylib/os/actions/convert_volume_to_image.py, cloudferrylib/os/actions/live_migration.py, cloudferrylib/os/compute/nova_compute.py, cloudferrylib/os/image/glance_image.py, cloudferrylib/os/storage/cinder_storage.py, tests/cloudferrylib/base/test_resource.py, tests/cloudferrylib/os/compute/test_nova.py
wait_for_status is used from base class for images, volumes and instances.
=> Fixed SAIC-387: refactoring for wait_for_status

cloudferrylib/utils/drivers/ssh_chunks.py, tests/cloudferrylib/utils/test_file_utils.py
File copy over SSH major issues resolved:
- Simplified logic;
- Configurability
=> SAIC-443 SSH file copy fix

cloudferrylib/os/actions/copy_g2g.py, cloudferrylib/os/image/glance_image.py, cloudferrylib/utils/file_like_proxy.py, requirements.txt, tests/cloudferrylib/os/actions/test_copy_g2g.py
Added new debug messages for image migration.
Added progress bar.
=> Fixed SAIC-373: image debug logs

cloudferrylib/os/actions/check_networks.py, cloudferrylib/os/network/neutron.py, devlab/tests/scenarios/cold_migrate.yaml, devlab/tests/scenarios/live_migrate.yaml, scenario/migrate.yaml, scenario/tasks.yaml, tests/cloudferrylib/os/actions/test_check_networks.py
Network overlapping check was added into `preparation` section in the end of `pre_migration_test`.
=> [SAIC-423] ClouldFerry fails migration if target subnet on dst exists

scenario/README.md, scenario/cold_migrate.yaml, scenario/migrate_resources.yaml, scenario/migrate_vms.yaml
Separated scenario for migration resources and VMs.
=> Fixed SAIC-380: documentation and scenarios

configs/config.ini
Hi Roman, 
I had some mess in my previous commit on branch devel. So i created and new branch devbr and will try to join their.
=> SAIC-425 Detailed description for CF configuration file.

cloudferrylib/os/actions/check_instance_networks.py, devlab/tests/scenarios/cold_migrate.yaml, devlab/tests/scenarios/live_migrate.yaml, scenario/cold_migrate.yaml, scenario/live_migrate.yaml, scenario/tasks.yaml, tests/cloudferrylib/os/actions/test_check_instance_networks.py
Verify is instance spawned directly in external network.
=> [SAIC-381] Check instance network

configs/config.ini
Also, fix several comments in `configs/config.ini`.
=> Minor fix: Add Network DB settings to main config

cloudferrylib/os/identity/keystone.py, cloudferrylib/os/image/glance_image.py
Adds logs for keystone and glance objects migration.
=> Improve logging for identity and image transfer

cloudferrylib/os/actions/check_cloud.py
Add test private network creation with subnet and use it to spawn test
VM. It is needed for cases, when there are multiple networks exist on
the cloud, that CF gonna check. And also to check booting VM in the
particular private network.
=> [SAIC-463] Fix CheckCloud action

devlab/tests/generate_load.py
Next resources are created in parallel: vms, vm snapshots, images
and volumes. It makes generate_load work more than in two times
faster. Also this resources have timeout, exceeded which will
raise Runtime error.
=> Refactored generate_load: Make resources spawn in parallel

devlab/utils/clean_run.sh, devlab/utils/deploy_lab.sh, devlab/utils/os_cli.sh
clean volumes works fine, define WORKSPACE for non-jenkins run and adde check for default lab usage
=> Fixed scripts

cloud/grouping.py, cloudferrylib/os/network/neutron.py, fabfile.py, tests/cloud/test_grouping.py, tests/cloudferrylib/os/network/test_neutron.py
Optimize VMs grouping by network with decreasing Neutron API calls.
Add 2 functions to `cloudferrylib.os.neutron.py` for obtaining Neutron
network from provided list of networks.
=> [SAIC-447] Grouping by network optimization

cloudferrylib/os/identity/keystone.py
Fixes identity migration when tenant filtering is enabled and
`optimize_user_role_fetch` option is set.
=> SAIC-484 Identity optimization with tenant filtering fix

cfglib.py, cloudferrylib/os/identity/keystone.py, configs/config.ini, tests/cloudferrylib/os/identity/test_keystone.py
Adds description for `optimize_user_role_fetch` config option.
=> Update config.ini with identity migration options

devlab/tests/test_resource_migration.py
Proposing fix for reference variable before assignment error.
=> Fixed copy paste error

cfglib.py, cloudferrylib/os/actions/check_ssh.py, cloudferrylib/os/actions/convert_file.py, cloudferrylib/os/actions/convert_image_to_file.py, cloudferrylib/os/actions/load_compute_image_to_file.py, cloudferrylib/os/actions/merge_base_and_diff.py, cloudferrylib/os/actions/pre_transport_instance.py, cloudferrylib/os/actions/transport_ephemeral.py, cloudferrylib/os/actions/upload_file_to_image.py, cloudferrylib/os/actions/utils.py, cloudferrylib/os/compute/instances.py, cloudferrylib/os/image/glance_image.py, cloudferrylib/os/network/nova_network.py, cloudferrylib/utils/drivers/ssh_ceph_to_ceph.py, cloudferrylib/utils/drivers/ssh_file_to_ceph.py, cloudferrylib/utils/drivers/ssh_file_to_file.py, cloudferrylib/utils/remote_runner.py, cloudferrylib/utils/utils.py, configs/config.ini, devlab/config.template, fabfile.py
For all Fabric SSH connections in the project.
=> [SAIC-416] Add `connection_attempts` option to config

devlab/tests/config.py, devlab/tests/functional_test.py, devlab/tests/generate_load.py, devlab/tests/test_resource_migration.py
Check gw ips of external router on src and dst are different.
=> SAIC-398 Added check router ips are not overlapping

cloudferrylib/os/actions/check_bandwidth.py
Documentation updated for bandwidth assessment class. Clarified config
option usage.
=> Update doc for bandwidth check

cloudferrylib/os/network/neutron.py
Checking existing floating ips and if ip is exist then pass
=> [SAIC-471]Fix bug in upload_floatingips

cloudferrylib/os/image/glance_image.py
Fix bug with incorrect transfer members src to dst
=> [SAIC-376]Correct members for images

cloudferrylib/utils/file_like_proxy.py
Progress bar works not properly during image migration
=> [SAIC-460]Progress bar

cloudferrylib/os/actions/check_users.py, cloudferrylib/os/image/glance_image.py, devlab/tests/scenarios/cold_migrate.yaml, devlab/tests/scenarios/live_migrate.yaml, scenario/cold_migrate.yaml, scenario/live_migrate.yaml, scenario/tasks.yaml
Glance images may have user ID stored in metadata, but user may not be
present on destination cloud. In order to avoid migration error
additional pre-migration check was added which verifies all users from
source are available on destination. This case is only applicable for
LDAP-backed clouds, since users usually are not created from keystone.
=> SAIC-557 Glance user in metadata

cloudferrylib/os/actions/filter_similar_vms_from_dst.py, devlab/tests/scenarios/cold_migrate.yaml, devlab/tests/scenarios/live_migrate.yaml, scenario/cold_migrate.yaml, scenario/live_migrate.yaml, scenario/migrate_vms.yaml, scenario/tasks.yaml, tests/cloudferrylib/os/actions/test_filter_similar_vms_from_dst.py
Also check if src instance ip overlaped by dst instances
=> [SAIC-499] Exclude instance if it exists on dst

.pylintrc
Added pylint config file. The file is based on openstack nova pylintrc.
=> Python static analysis configuration

cfglib.py, cloudferrylib/os/actions/check_config_quota_neutron.py, cloudferrylib/os/identity/keystone.py, cloudferrylib/os/network/neutron.py, devlab/tests/config.py, devlab/tests/generate_load.py, devlab/tests/scenarios/cold_migrate.yaml, scenario/cold_migrate.yaml, scenario/tasks.yaml, tests/cloudferrylib/os/network/test_neutron.py
It has a function of getting quotas and their loading.
Implemented unit tests.
=> [SAIC-308]Migrate quotas network

scenario/prechecks.yaml
This scenario only checks if CF is setup correctly prior to migration
and all prerequisites for source and destination clouds have been met.
=> Added scenario for CF Initial setup verification.

docs/CloudFerry_Beginner_Demo_How-To.md, docs/README
Documentation is primarily targeted at deployment engineers starting to work
with cloudferry.
=> Adding beginner documentation in markdown format

cloudferrylib/os/identity/keystone.py, cloudferrylib/os/image/glance_image.py, cloudferrylib/utils/file_like_proxy.py, tests/cloudferrylib/os/image/test_glance_image.py
Resolves bug with glance image migration when one of the images does not
have checksum.
=> SAIC-571 Glance image migration without checksum

cloudferrylib/os/network/neutron.py
Add the subnets from the shared networks.
Filter the routers by the subnets.
=> SAIC-602 Fix the filtering by tenant id

cloudferrylib/os/identity/keystone.py
This fix solves ''unhashable type dict' error in _get_user_tenants_roles_by_db method of Identity CF resource.
=> little fix for Identity resource

cfglib.py, cloud/cloud.py, cloudferrylib/base/resource.py, cloudferrylib/os/compute/cold_evacuate.py, cloudferrylib/os/compute/nova_compute.py, cloudferrylib/utils/remote_runner.py, configs/config.ini, tests/cloudferrylib/os/compute/test_cold_evacuate.py
Cold evacuation consists of following steps:
1) Add SSH keys for nova user to source and destination
2) Disable all nova-compute services except source and destination
3) Do nova migrate
4) Enable previously disabled nova-compute services
5) Remove SSH keys from source and destination
=> SAIC-554 cold evacuation support

devlab/tests/config.py, devlab/tests/generate_load.py
Removed admin roles assigning while creating tenants.
Added user with admin role to one of the tenants.
Fixed some of pylint issues.
=> [SAIC-580] Remove admin roles from tenants

scenario/cold_migrate_autorollback.yaml, scenario/migrate_resources_autorollback.yaml, scenario/migrate_vms.yaml, scenario/stages/0_prechecks.yaml, scenario/stages/1_checkcloud.yaml, scenario/stages/2_identity_transporter.yaml, scenario/stages/3_get_and_transfer_images.yaml, scenario/stages/4_transport_compute_resources.yaml, scenario/stages/5_network_transporter.yaml, scenario/stages/6_get_transfer_volumes.yaml, scenario/stages/7_transport_keypairs.yaml
Add CF scenarios for resource migration in stages.
Add CF scenarios for `Cold_migrate` and `Migrate_resources` with
autorollback for testing purposes.
Fix rollback steps for Migrate_resources scenario.
=> [SAIC-536] CF scenarios: migration in stages.

cloudferrylib/os/image/glance_image.py
Raise ImageDownloadError instead of HTTPNotFound
=> [SAIC-677] Fix glance images deployment

cloudferrylib/os/network/neutron.py
Words ala `append` changed to
`Got`
=> [SAIC-654] Improve Neutron logs

cloudferrylib/os/actions/check_cloud.py, devlab/tests/scenarios/cold_migrate.yaml, devlab/tests/scenarios/live_migrate.yaml, scenario/cold_migrate.yaml, scenario/live_migrate.yaml
Fully reworked check_cloud action.
=> SAIC-675 Invalid flavorRef while running checks.

cloud/os2os.py, cloudferrylib/scheduler/scheduler.py, cloudferrylib/utils/errorcodes.py, fabfile.py
0 - Migration finished successfully
1 - Initial check failed(PREPARATION SECTION)
2 - Invalid configuration(Any exception oslo.configs)
3 - Migration failed, rolled back(MIGRATION SECTION)
4 - Error during rollback(ROLLBACK SECTION)
=> [SAIC-546] Set nonzero exit code if migration finished with failure

cfglib.py, cloudferrylib/os/actions/attach_used_volumes_via_compute.py, cloudferrylib/os/actions/check_filter.py, cloudferrylib/os/actions/cinder_database_manipulation.py, cloudferrylib/os/actions/get_filter.py, cloudferrylib/os/storage/cinder_database.py, cloudferrylib/os/storage/cinder_storage.py, cloudferrylib/os/storage/filters.py, cloudferrylib/utils/filters.py, cloudferrylib/utils/remote_runner.py, configs/filter.yaml, devlab/tests/config.py, devlab/tests/generate_load.py, test-requirements.txt, tests/cloudferrylib/os/actions/test_cinder_database_manipulation.py, tests/cloudferrylib/os/storage/test_cinder_filters.py, tests/cloudferrylib/utils/test_runner.py
Cinder volume migration for multiple nfs backends.
Fix pylint issues.
Remove snapshot migration.
=> SAIC-543: Cinder volume migration

cloudferrylib/os/actions/check_cloud.py
Changed all debug messages to info.
=> Check cloud logging improvements.

cfglib.py, cloudferrylib/os/actions/snapshots.py, cloudferrylib/utils/utils.py, tests/cloudferrylib/utils/test_utils.py
Now we can use several ssh private keys, f.e. different keys for
source and destinashion clouds.
=> Added an ability for using multiple ssh keys

cloudferrylib/os/image/glance_image.py
Check if 'user_name' property exists before update 'user_id' property
in glance deploy function.
=> [SAIC-735] Check 'user_name' property in glance

cloudferrylib/os/image/glance_image.py
Improve existing image detection by adding check for tenant_id and
is_public fields.
=> [SAIC-726] Improve existing image detection.

cloudferrylib/utils/qemu_img.py, tests/cloudferrylib/utils/test_qemu_img.py
Support older versions of qemu-img as well as newer. More recent
versions of qemu-img (v2.0.0) come with support for JSON output,
which is not available in the older versions.
=> SAIC-672 Support JSON and human output for qemu-img

cloudferrylib/os/actions/check_networks.py, cloudferrylib/os/network/neutron.py, tests/cloudferrylib/os/actions/test_check_networks.py, tests/cloudferrylib/os/network/test_neutron.py
[SAIC-651] Allow Neutron segmentation IDs overlap
=> [SAIC-651] Allow Neutron segmentation IDs overlap

cloudferrylib/os/actions/filter_similar_vms_from_dst.py
Exclude deleted tenant while check existing VMs on DST.
=> [SAIC-608] Exclude deleted tenant

devlab/tests/config.py, devlab/tests/test_verify_dst_del_tenant_resources.py
Migrate deleted tenant's openstack objects.
=> [SAIC-569] Verify openstack objects of deleted tenant on DST

devlab/tests/generate_load.py, devlab/tests/test_verify_dst_functionality.py
Added wait for vm deletion in tearDown method of
test_verify_dst_functionality.
=> SAIC-748 Fixed issue in tearDown test_verify_dst_functionality

devlab/tests/functional_test.py, devlab/tests/test_verify_dst_del_tenant_resources.py, devlab/tests/test_vm_migration.py, devlab/tests/utils.py
Included is_tenant deleted checks.
=> SAIC-779 Fix FT to ignore deleted tenant's resources.

cloudferrylib/os/image/glance_image.py, cloudferrylib/utils/sizeof_format.py, tests/cloudferrylib/utils/test_sizeof_format.py
Show information about total number of images to be migrated, total size,
progress of migration.
=> [SAIC-760] Show the global progress of the image migration

cloudferrylib/os/image/glance_image.py
Raise ImageDownloadError instead of IncompleteRead exception.
=> [SAIC-780] Skip the broken images

cloudferrylib/os/image/glance_image.py
Glance image migration fails with KeyError: 'owner_name' on the Devlab.
(Regression bug caused by SAIC-760.)
=> SAIC-789 Fix broken CopyFromGlanceToGlance

devlab/tests/config.py, devlab/tests/functional_test.py, devlab/tests/generate_load.py, devlab/tests/test_exceptions.py, devlab/tests/test_verify_dst_functionality.py, test-requirements.txt
Extend functional tests to verify migration 
when source and destination migration tenants are different
=> [SAIC-453] Extend func tests due to different admin tenants migration

cloudferrylib/os/actions/transport_compute_resources.py
Added functionality which allows to search destination user by source user only one time. It should help to reduce time of keypairs migration.
=> [SAIC-793] Improve keypairs migration speed.

cloudferrylib/base/resource.py, cloudferrylib/os/actions/remove_failed_instances.py, cloudferrylib/os/compute/nova_compute.py, devlab/tests/scenarios/cold_migrate.yaml, scenario/cold_migrate.yaml, scenario/tasks.yaml
Save IDs of all faliled instances and try to delete those.
Add additional task to virify that all failed instances were deleted.
=> [SAIC-736] Remove instances which are failed by timeout

devlab/tests/config.py, devlab/tests/functional_test.py, devlab/tests/generate_load.py, devlab/tests/test_resource_migration.py
Added public and private flavors to created tenants.
=> SAIC-757 Extend FT with non-public flavors migration.

devlab/tests/config.py, devlab/tests/functional_test.py, devlab/tests/generate_load.py, devlab/tests/test_resource_migration.py
Added user's routers generation.
Reworked network topologies for tenants.
Added test to check router presents once.
=> SAIC-790 Automated test for router migration

cfglib.py, cloudferrylib/os/compute/nova_compute.py, configs/config.ini
Make a timeout value of checking is VM active configurable.
=> [SAIC-820] Add boot_timeout option

cfglib.py, cloudferrylib/os/identity/keystone.py, cloudferrylib/os/network/neutron.py, devlab/tests/config.py, devlab/tests/generate_load.py, tests/cloudferrylib/os/network/test_neutron.py
Fixed bugs in current implementation migration LBaaS objects.
Added unit-test for deploy lbaas objects.
Added migration neutron objects by tenant.
=> [SAIC-551] LBaaS neutron objects migration

devlab/tests/test_group_verification.py, devlab/tests/test_resource_migration.py, devlab/tests/test_verify_dst_del_tenant_resources.py, devlab/tests/test_verify_dst_functionality.py, devlab/tests/test_vm_migration.py
Added nosetests attributes for specific tests.
Added lost licenses in files with tests.
Optimized imports in tests.
=> SAIC-828 Add specific tests execution after each tenant migration.

cloudferrylib/os/actions/vm_snapshot.py, devlab/tests/scenarios/cold_migrate.yaml, scenario/cold_migrate.yaml, scenario/cold_migrate_autorollback.yaml, scenario/migrate_vms.yaml, scenario/tasks.yaml
Created action CheckPointVm. This action
checking successfully miragte vm. Rollback ignores
successfully migrate vms
=> [SAIC-756] Granular VM restore from snapshot for src and dst

devlab/tests/config.py, devlab/tests/generate_load.py, devlab/tests/test_resource_migration.py, devlab/tests/test_verify_dst_net_segm_id.py
Extend functional tests to verify network segmentation IDs overlap
=> [SAIC-761] Verify network segmentation IDs overlap

cloudferrylib/os/image/glance_image.py
Tenants required to be migrated before migration of glance images
are all the members of glance images, not only owners.
If a tenant-member is not migrated then a membership update fails.
=> SAIC-803 Glance images members as required tenants

scenario/stages_without_rollback/0_prechecks.yaml, scenario/stages_without_rollback/1_checkcloud.yaml, scenario/stages_without_rollback/2_identity_transporter.yaml, scenario/stages_without_rollback/3_get_and_transfer_images.yaml, scenario/stages_without_rollback/4_transport_compute_resources.yaml, scenario/stages_without_rollback/5_network_transporter.yaml, scenario/stages_without_rollback/6_get_transfer_volumes.yaml, scenario/stages_without_rollback/7_transport_keypairs.yaml, scenario/stages_without_rollback/8_migrate_server_groups.yaml, scenario/stages_without_rollback/migrate_vms.yaml
Add CF scenarios for resources and VM migration with NO Rollback.
=> [SAIC-755] CF scenarios with disabled Rollback.

QUICKSTART.md, docs/CloudFerry_Beginner_Demo_How-To.md
Change the documentation to use 7.1.2 version.
=> Use 7.1.2 version of pip

cloudferrylib/os/network/neutron.py
Adds support for SNAT property of external routers which was introduced
in icehouse release of neutron.
=> CF-26 SNAT support for external routers

devlab/tests/config.py, devlab/tests/generate_load.py
Added member to image6, image with deleted tenant.
=> CF-48 check if image with deleted primary tenant migrates successfully.

cloudferrylib/os/actions/check_affinity.py
Removes unnecessary retries for nova affinity APIs if those are not
available.
=> CF-132 Reduce number of nova API requests for CheckAffinity

devlab/tests/test_resource_migration.py
Changed test_migrate_glance_belongs_to_deleted_tenant test.
=> CF-136 test_migrate_glance_belongs_to_deleted_tenant fails.

cloudferrylib/utils/drivers/copy_engine.py
Previous code did not clean up after itself leaving multiple temporary files behind.
=> CF-135 Remove temp files for scp backend

devlab/Vagrantfile
=> Increase RAM for nfs VM

Dockerfile, README.md
As a DE, I would like to run CF as docker to simplify CF installation
=> CF-140 Dockerfile for cloudferry.

scenario/stages_without_rollback/0_prechecks.yaml, scenario/stages_without_rollback/1_checkcloud.yaml, scenario/stages_without_rollback/3_get_and_transfer_images.yaml, scenario/stages_without_rollback/5_network_transporter.yaml, scenario/stages_without_rollback/6_get_transfer_volumes.yaml, scenario/stages_without_rollback/7_transport_keypairs.yaml, scenario/stages_without_rollback/migrate_vms.yaml
SAIC-755 Minor Fixes for stages with no rollback.
=> Fixes for stages with no rollback

cloudferrylib/base/resource.py, cloudferrylib/os/identity/keystone.py, cloudferrylib/os/image/glance_image.py, cloudferrylib/os/network/neutron.py
filter_tenant_id variable is initializing in read_info function, but it's also necessary in required_tenant function as well.
=> [CF-17] Fix required_tenants function

devlab/Vagrantfile, devlab/config.ini, devlab/provision/fix_interfaces.sh
Need for multi network support [CF-109]
=> Add second private network to devlab

cloudferrylib/base/action/get_info_iter.py, tests/cloudferrylib/base/test_migration_progress_view.py
Improves VM migration progress presentation to user.
=> CF-89 Show VM progress

cloudferrylib/os/actions/check_config_quota_neutron.py
Fix code to make create tenant requests to destination cloud instead of
source.
=> [CF-168] Fix neutron quota precheck

cloudferrylib/os/compute/instance_info_caches.py, cloudferrylib/os/compute/nova_compute.py
Do not sort network interfaces if no data in instance_info_caches
=> [CF-110] Fix key error exception

cloudferrylib/scheduler/scheduler.py, cloudferrylib/utils/log.py, configs/logging_config.yaml
Write all log messages into debug.log file.
Mute not cloudferry messages for console and info.log file.
=> Improve logging

cloudferrylib/os/actions/cinder_database_manipulation.py, cloudferrylib/views/cinder_storage_view.py, tests/cloudferrylib/os/actions/test_cinder_database_manipulation.py
Add some output information in logs about global migration
process of Cinder volumes.
=> [CF-87] Show global progress of Cinder Volume migration

cloudferrylib/utils/log.py, configs/logging_config.yaml
Fix the problem the debug-*.log files doesn't contain cloudferry logs.
=> [CF-198] Write ALL information into debug log file

cloudferrylib/scheduler/scenario.py, cloudferrylib/utils/extensions.py
Implement module to dynamically load the extensions.
The current implementation is importing modules as the root modules,
does not keep the paths of the modules.
=> [CF-198] Fix importing of actions

devlab/tests/cleanup.py, devlab/tests/config.py, devlab/tests/generate_load.py
Modified generate_load to use CF logger instead of print.
=> CF-170 generate_load hangs without generating anything.

cloudferrylib/utils/log.py, configs/logging_config.yaml
Forward the stdout messages into log with INFO level
=> [CF-198] Write stdout to log

cloudferrylib/utils/local.py
Introduces library for local calls
=> Library for local command execution

scenario/stages_without_rollback/0_prechecks.yaml, scenario/stages_without_rollback/1_checkcloud.yaml, scenario/stages_without_rollback/2_identity_transporter.yaml, scenario/stages_without_rollback/3_get_and_transfer_images.yaml, scenario/stages_without_rollback/4_transport_compute_resources.yaml, scenario/stages_without_rollback/5_network_transporter.yaml, scenario/stages_without_rollback/6_get_transfer_volumes.yaml, scenario/stages_without_rollback/7_transport_keypairs.yaml, scenario/stages_without_rollback/hybrid_resource_migration.yaml, scenario/stages_without_rollback/migrate_vms.yaml
1. Hybrid resource migration scenario with no rollbacks, which migrates
resources that don't require time-consuming transfers (volumes, images).
Following resources going to be migrated in this scenario: identity,
compute, keypairs, networks.
2. Added print info for configurations, scenario and filters to be viewed
in logs for scenarios with no rollbacks.
=> [CF-222] Hybrid resource migration scenario.

devlab/tests/testcases/test_resource_migration.py
Removed servers group test execution after 'admin' tenant migration.
=> CF-224 AssertionError: Members in server group.

cfglib.py, cloudferrylib/os/actions/check_quotas.py, cloudferrylib/os/compute/nova_compute.py, cloudferrylib/os/compute/usage_quota.py, configs/config.ini, devlab/config.template, devlab/tests/scenarios/cold_migrate.yaml, scenario/cold_migrate.yaml, scenario/tasks.yaml, tests/cloudferrylib/os/compute/test_nova.py
- Implemented change of usage quotas
for instances (cores, ram, instances)
=> [CF-108] Migrate nova usage quotas

cloudferrylib/utils/retrying.py, tests/cloudferrylib/utils/test_retrying.py
Introduces a library which handles multiple common cases of retry logic
=> Retrying library

devlab/tests/testcases/test_resource_migration.py
Added image id parameter to resource validation.
=> CF-174 verify glance image UUIDs are kept the same

cloudferrylib/os/actions/snapshots.py
This fix checks DB password and if it's empty, we are not using '--password' option for mysql and mysqldump commands.
=> [CF-21] Check mysql db password for db snapshot/restore commands

cfglib.py, cloudferrylib/os/compute/nova_compute.py, cloudferrylib/utils/override.py, configs/config.ini, configs/override_rules.yaml, tests/cloudferrylib/os/compute/test_nova.py, tests/cloudferrylib/utils/test_override.py
This patch add mechanism to override various VM instance attributes
including server groups, availability zones, flavors, etc...
=> [CF-99] Add attribute override ability

cloudferrylib/os/network/neutron.py
Exclude external subnets at the right moment from the list of subnets,
that should be added to router interfaces. They are used for setting
up external network gateway for router.
Also rename several variables for better readability.
=> [CF-191] Fix external networks mapping

devlab/generate_load.py, devlab/tests/base.py
- Get rid of removing items from list which it iterates on, this may not always work as expected;
- All the {{wait_until_.*}} methods have very similar if not the same implementation, thus need to be generalized and moved to a single method.
=> cf-252 Change wait_until_* methods to not remove from list.

devlab/generate_load.py, devlab/tests/config.py
Added new VM to generate_load.py script with deleted image. Image
should be deleted correctly via glance API.
=> CF-259 Add VM to generate_load with deleted image.

devlab/docs/autotests.rst, devlab/docs/doc-requirements.txt, devlab/docs/index.rst, docs/configuration.rst, docs/glance_image_migration.rst, docs/index.rst, docs/installation.rst, docs/overview.rst, docs/quick_start_guide.rst
Adds user-oriented documentation for CloudFerry in rst format.
Following topics are described:
- Generic overview;
- Installation;
- Quick start guide;
- Configuration overview.
=> CF-288 Documentation

cloudferrylib/os/actions/verify_vms.py
adding in failed_vms if only vm don't found in dst
=> [CF-161] VerifyVms shows incorrect results

cloudferrylib/copy_engines/bbcp_copier.py, cloudferrylib/os/actions/task_transfer.py, cloudferrylib/utils/ssh_util.py
Add default ssh options to bbcp command.
Check a usage of copier for TaskTransfer action transfer a data.
=> [CF-279] Specify command to start bbcp on remote host

devlab/tests/config.py
Update network range to use cidr from br-ex2, eth2
CF-295
=> Update network range to use cidr from br-ex2, eth2

devlab/tests/base.py, devlab/tests/testcases/test_verify_dst_functionality.py
- Moved duplicated checks to separate methods
- Added floating IP assignment check and retry
- Added vm.name logging when fail occurs
=> CF-296 Refactor test_verify_dst_functionality.py

devlab/tests/scenarios/live_migrate.yaml, scenario/cold_migrate.yaml, scenario/cold_migrate_autorollback.yaml, scenario/live_migrate.yaml, scenario/migrate_resources.yaml, scenario/migrate_resources_autorollback.yaml, scenario/migrate_vms.yaml, scenario/stages/0_prechecks.yaml, scenario/stages/1_checkcloud.yaml, scenario/stages/2_identity_transporter.yaml, scenario/stages/3_get_and_transfer_images.yaml, scenario/stages/4_transport_compute_resources.yaml, scenario/stages/5_network_transporter.yaml, scenario/stages/6_migrate_volumes.yaml, scenario/stages/7_transport_keypairs.yaml, scenario/stages/8_migrate_server_groups.yaml, scenario/stages_without_rollback/0_prechecks.yaml, scenario/stages_without_rollback/1_checkcloud.yaml, scenario/stages_without_rollback/2_identity_transporter.yaml, scenario/stages_without_rollback/3_get_and_transfer_images.yaml, scenario/stages_without_rollback/4_transport_compute_resources.yaml, scenario/stages_without_rollback/5_network_transporter.yaml, scenario/stages_without_rollback/6_migrate_volumes.yaml, scenario/stages_without_rollback/7_transport_keypairs.yaml, scenario/stages_without_rollback/8_migrate_server_groups.yaml, scenario/stages_without_rollback/hybrid_resource_migration.yaml, scenario/stages_without_rollback/migrate_vms.yaml
Add section with priting an additional information into preparation
section of each scenario.
=> Print additional information for each scenario

cloudferrylib/os/identity/keystone.py, tests/cloudferrylib/os/identity/test_keystone.py
Sometimes during authorization process we can get some exception,
raised by some temporary conditions: network instability, auth-backend
unavailability and others not related to wrong credentials.
When this encountered, cloudferry lack handling of such situations.
This patch provides fix for above situations.
=> Fix for CF-10 : keystone exception handling

cloudferrylib/os/actions/transport_storage_resources.py, cloudferrylib/os/storage/cinder_storage.py, devlab/tests/scenarios/cold_migrate.yaml, scenario/cold_migrate.yaml, scenario/stages/6_migrate_volumes.yaml, scenario/tasks.yaml
Added reading and deploying cinder quotas
=> [CF-235]Copy cinder quotas

devlab/generate_load.py, devlab/tests/config.py
Fixed dst_cloud object initialization.
Added external router generation on dst, and network assignment.
=> CF-295 update tests to create external neutron router.

cloudferrylib/os/actions/migrate_volumes.py
Modifies logic to correctly remove volumes which failed to migrate for
any reason.
=> CF-330 Remove failed volumes

cloudferrylib/os/compute/nova_compute.py
Add logs with skipped Nova Compute hosts, if they are disabled or down.
Add logs with skipped VMs, if they are running on non-active (status is
`disabled` or state is `down`) Nova Compute hosts.
=> [CF-312] Extend NovaCompute resource logs

devlab/tests/testcases/test_resource_migration.py
Scenario:
1. Get volumes on which data was written
2. Get floating ip address of vm, to which volume attached
3. Open TCP/22 port for vm's tenant,
4. Wait until vm accessible via ssh
5. Check mount point has been migrated with ephemeral storage
6. Mount volume
7. Check data on volume is correct
=> [FT] CF-61 Add check for ephemeral storage migration

docs/user/identity.rst, docs/user/user_doc_index.rst
Adds documentation for keystone objects migration:
- tenants;
- user roles.
=> CF-302 Identity migration documentation

cloudferrylib/os/image/glance_image.py, tests/cloudferrylib/os/image/test_glance_image.py
=> [CF-271] Migrate image of vm if it's not specified in filter

cloudferrylib/os/actions/check_cloud.py
Create most of objects in the randomly created tenant instead of admin
tenant (except of public resources, such as shared external network and
image).
Fix action's logs and error messages.
=> [CF-343] Fix `CheckCloud` action

cloudferry_devlab/cloudferry_devlab/generate_load.py, cloudferry_devlab/cloudferry_devlab/tests/base.py, cloudferry_devlab/cloudferry_devlab/tests/cleanup.py, cloudferry_devlab/cloudferry_devlab/tests/config.py
Add functionality to generate swift containers and objects
on source cloud with random content. All parameters
for containers and objects can specify in the config file.
=> [CF-240] Extend generate load to generate swift objects

cloudferrylib/os/image/glance_image.py
Keystone sporadically fails with 401 Unauthorized during glance image
migration even though all credentials are correct. Resolved by adding
retries at the point of failure.
=> CF-385 Unauthorized errors during glance image migration

cloudferry_devlab/cloudferry_devlab/tests/config.py, cloudferry_devlab/cloudferry_devlab/tests/testcases/test_resource_migration.py
Created subnet with dns_nameservers attribute in source cloud.
Verified dns_nameservers attribute migrated to destination.
Refactored params validation in test_resource_migration.
=> CF-364 Verify migration of dns_nameservers in subnets.

cloudferrylib/os/actions/is_not_copy_diff_file.py, cloudferrylib/os/actions/transport_instance.py, cloudferrylib/os/image/glance_image.py
Instance migration would fail if image in destination is deleted
using glance API, but exists in DB.
=> CF-375 CF instance migration does not consider existing images

cloudferry_devlab/cloudferry_devlab/generate_load.py, cloudferry_devlab/cloudferry_devlab/tests/config.py, cloudferry_devlab/cloudferry_devlab/tests/testcases/test_resource_migration.py, cloudferry_devlab/cloudferry_devlab/tests/testcases/test_verify_dst_functionality.py, cloudferry_devlab/cloudferry_devlab/tests/utils.py
Fixed VM accessability by floating IP in generate_load.py
=> CF-398 Improving waiting VM accessibility by SSH in generate load.

cloudferry_devlab/cloudferry_devlab/generate_load.py
- Create separate filter file for each tenant in config.py (including admin tenant, and excluding tenants, which are deleted on src ( field "deleted": True in config.py))
- Filter files should have name 'filter_{tenant_name}.yaml'
- Each filter should contain lists of images, instances and volumes, which are belong to given tenant (except instances and images, which should not be included in the filter according to config.py, `images_not_included_in_filter` and `vms_not_in_filter`)
- 'images' section should contain parameter 'dont_include_public_and_members_from_other_tenants': False
=> CF-358 Need to refactor 'update_filtering_file' method

cloudferry_devlab/cloudferry_devlab/tests/config.py
Test scenario:
- Create image in source cloud
- Boot VM from that image
- Create the same (same name, ID, md5, tenant) image in destination cloud
- Delete image from destination cloud using Glance APIs
- Create same image in destination again, but with different ID
- Run VM migration
- Verify that VM was booted from image created in destination cloud in step 5.
=> CF-400 Verify deleted image which have the same IDs as images in SRC

cloudferry/fabfile.py, cloudferry/lib/config.py, cloudferry/lib/os/clients.py, cloudferry/lib/os/cloud_db.py, cloudferry/lib/os/discovery/cinder.py, cloudferry/lib/os/discovery/glance.py, cloudferry/lib/os/discovery/keystone.py, cloudferry/lib/os/discovery/model.py, cloudferry/lib/os/discovery/nova.py, cloudferry/lib/os/discovery/stages.py, cloudferry/lib/os/migrate/base.py, cloudferry/lib/os/migrate/glance.py, cloudferry/lib/os/migrate/keystone.py, cloudferry/lib/utils/local_db.py, cloudferry/lib/utils/qemu_img.py, cloudferry/lib/utils/remote.py, cloudferry/lib/utils/taskflow_utils.py, cloudferry/lib/utils/utils.py, requirements.txt, tests/lib/os/discovery/test_model.py
TaskFlow library make possible to create parallel restartable task flow system. After this patch it will be possible to migrate several images in parallel.
=> TaskFlow-based tenant and image migration

cloudferry_devlab/cloudferry_devlab/generate_load.py, cloudferry_devlab/cloudferry_devlab/tests/config.py
Below scenario is added to the functional tests.
* Create VM with config_drive attribute in source cloud;
* Run migration
* Verify config_drive attribute migrated successfully
=> [CF-333] Extend functional tests to verify migration of config_drive VM attribute

cloudferry_devlab/cloudferry_devlab/generate_load.py
Fixed delete_image_on_dst flag logic to try to delete image using ID
from config.py first.
=> CF-453 Image migration failed with invalid ID.

setup.cfg, setup.py
Use setup.cfg file instead of setup.py
=> [CF-454] Use pbr library

cloudferry/lib/config.py, cloudferry/lib/os/discovery/glance.py, cloudferry/lib/os/discovery/model.py, cloudferry/lib/os/discovery/nova.py, cloudferry/lib/os/migrate/base.py, cloudferry/lib/os/migrate/glance.py, cloudferry/lib/os/migrate/keystone.py, cloudferry/lib/utils/remote.py, cloudferry/lib/utils/taskflow_utils.py
This patch adds support for image member migration as part of v2 migration.
=> [CF-436] Add ImageMember migration.

cloudferry/lib/os/network/network_utils.py
The bug was introduced which caused all subnets change its enable_dhcp to
False during VM migration. This patch fixes this.
=> [CF-458] Set enable_dhcp to original value on destination.

cloudferry/cli/v2/commands.py, cloudferry/lib/os/estimation/procedures.py, setup.cfg
Query command allows testing of jmespath.
=> [CF-356] Implement query command

cloudferry_devlab/Vagrantfile, cloudferry_devlab/provision/configure_networking.sh, cloudferry_devlab/provision/configure_openstack.sh
This patch improve devlab load time by removing unnecessary steps
like updating apt repository, trying to install packages that are
already installed, etc...
=> [CF-439] Improve devlab VM load time

cloudferry_devlab/Vagrantfile, cloudferry_devlab/cloudferry_devlab/tests/utils.py, cloudferry_devlab/provision/configure_openstack.sh
=> [CF-439] Fix vagrantfile not working

cloudferry_devlab/cloudferry_devlab/tests/config.py
Moved 'enable_dhcp=False' to t3_s1 subnet.
=> CF-470 Wrong subnet chosen for enable_dhcp=False parameter.

cloudferry/lib/os/image/glance_image.py
Add handling of HTTP 504 to glance migration code.
=> [CF-475] Add handling oh HTTP 504 to glance.

cloudferry/lib/os/storage/cinder_storage.py
=> [CF-465] Fix checking that quotas are identical

cloudferry/cli/base.py, cloudferry/lib/utils/log.py
Call disable_warnings function to hide all ssl warnings.
=> [CF-482] Hide ssl warnings

cloudferry/lib/os/storage/plugins/copy_mechanisms.py
When doing command piping like this: 'dd of=in_file | ssh user@host dd of=out_file', it will not work if user don't have access to this file. Also, we can't use sudo since it's in different cloud and password can differ from password on source cloud. So the only way to implement this without terrible hacks is through nc.
=> [CF-429] Fix cinder migration using non-root user

cloudferry_devlab/cloudferry_devlab/generate_load.py, cloudferry_devlab/cloudferry_devlab/tests/base.py, cloudferry_devlab/cloudferry_devlab/tests/config.py
Optimized VM's usage on both SRC and DST.
=> CF-504 Reduce amount of VMs used for devlab environment.

cloudferry_devlab/cloudferry_devlab/tests/functional_test.py
Fixed is_public parameter for src image list.
=> CF-515 FT jobs is failing with 'Nothing to migrate' error.

cloudferry/lib/os/actions/attach_used_volumes_via_compute.py
Use expect_exception to have a faster and better behavior of AttachVolumesCompute action.
=> Use expect_exception for AttachVolumesCompute

cloudferry/cli/base.py, cloudferry/config.py, cloudferry/discover.py, cloudferry/lib/utils/bases.py, tests/lib/utils/test_bases.py, tests/test.py, tests/test_config.py
This patch validate configuration file more strictly, not passing
values that are not specified in schema. Also for fields that
specify class names the classes are loaded early in order to
detect error loading module/class during field validation and not
during object initialization.
=> [CF-430] Improve configuration validation

cloudferry_devlab/cloudferry_devlab/bin/main.py, cloudferry_devlab/cloudferry_devlab/generate_load.py, cloudferry_devlab/cloudferry_devlab/tests/base.py, cloudferry_devlab/cloudferry_devlab/tests/config.py, cloudferry_devlab/setup.py
Added script, whic is able to restore correct states of VMs
which are already present in the box.
=> CF-510 Script to start VMs which are powered off.

cloudferry_devlab/cloudferry_devlab/generate_load.py
Added shutting off step to the run_restore_vms_state scenario.
=> Shutting VMs off before returning their state.

cloudferry_devlab/cloudferry_devlab/generate_load.py, cloudferry_devlab/cloudferry_devlab/tests/config.py, cloudferry_devlab/cloudferry_devlab/tests/functional_test.py, cloudferry_devlab/cloudferry_devlab/tests/testcases/test_vm_migration.py
Removed pre_migration_vm_states.json file generation and usage.
=> CF-513 Refactor functional tests to remove unnecessary dependencies.

cloudferry/cfglib.py, cloudferry/lib/copy_engines/bbcp_copier.py, cloudferry/lib/copy_engines/rsync_copier.py, cloudferry/lib/os/actions/check_copy_engine_configuration.py, scenario/cold_migrate.yaml, scenario/stages/0_prechecks.yaml, scenario/stages_without_rollback/0_prechecks.yaml, scenario/tasks.yaml
Check that bbcp files exist.
Warn if rsync port option has a default value if direct_trasfer is enabled.
=> [CF-448] Checking the configuration of copy engines

cloudferry_devlab/cloudferry_devlab/generate_load.py, cloudferry_devlab/cloudferry_devlab/tests/base.py, cloudferry_devlab/cloudferry_devlab/tests/testcases/test_verify_dst_functionality.py
Reworked create_all_vms method to include:
* attach floating ip,
* attach volume and generate data,
* emulate status of VM.
=> CF-509 generate_load.py to create VMs sequentially.

cloudferry_devlab/cloudferry_devlab/generate_load.py
Fixed create_vms_on_dst method.
=> Fix for CF-509 proper creation DST VMs.

QUICKSTART.md, README.md
Updates README.md and QUICKSTART.md with correct documentation.
=> CF-532 Update outdated documentation

cloudferry_devlab/requirements.txt
Fixed requirements for cloudferry_devlab.
=> CF-541 generate_load script fails

cloudferry_devlab/cloudferry_devlab/generate_load.py, cloudferry_devlab/cloudferry_devlab/tests/base.py, cloudferry_devlab/cloudferry_devlab/tests/config.py, cloudferry_devlab/cloudferry_devlab/tests/testcases/test_keystone_migration.py, cloudferry_devlab/cloudferry_devlab/tests/testcases/test_nova_resource_migration.py
1) Below scenario added to functional tests (CF-219)
- Create user and tenant in source cloud
- Create user and tenant with the same names in the uppercase in destination
- Create user roles for the user created on source cloud
- Run identity migration
- Verify user roles migrated correctly for the "case insensitive" user/tenant (CF-420)
2) Fix functional test failure messages (CF-455)
3) With tenant filter applied, functional tests should verify identity migration for that tenant (CF-408)
=> [CF-219,420,408,455]  Add Tests to verify migration of Users & tenants names in different cases

cloudferry_devlab/cloudferry_devlab/generate_load.py, cloudferry_devlab/cloudferry_devlab/tests/base.py, cloudferry_devlab/cloudferry_devlab/tests/cleanup.py, cloudferry_devlab/cloudferry_devlab/tests/functional_test.py, cloudferry_devlab/cloudferry_devlab/tests/testcases/test_vm_migration.py, cloudferry_devlab/cloudferry_devlab/tests/utils.py
Refactored the filtering utils for source VM filtering.
Accordingly incorporated the changes in the VM functional tests.
=> [CF-544] Refactor filtering utils to include proper VMs filtering

cloudferry_devlab/cloudferry_devlab/generate_load.py
Fixed username and password to get from configuration.ini
=> CF-522 Modify auto tests to run migration as non-root user.

cloudferry_devlab/cloudferry_devlab/generate_load.py
Reverts MirantisWorkloadMobility/CloudFerry#1058
=> Revert "CF-522 Modify auto tests to run migration as non-root user."

cloudferry/model/__init__.py, tests/model/test_model.py
This patch fixes issue found in production environment where there
was attachment to server that wasn't saved to database (probably due
to it's state or something else). The link stage thrown exception
failing to find server. This patch fixes the problem.
=> [CF-508] Support absent references during link stage

cloudferry_devlab/cloudferry_devlab/generate_load.py, cloudferry_devlab/cloudferry_devlab/tests/base.py, cloudferry_devlab/cloudferry_devlab/tests/config.py, cloudferry_devlab/cloudferry_devlab/tests/utils.py
Added generate_load.log file and log handler.
Moved couple of constants to config.py
Extended logging in generate_load and base.py
=> CF-562 Add debug logs to generate_load.

cloudferry/cfglib.py, cloudferry/lib/base/resource.py, cloudferry/lib/os/image/glance_image.py, configs/config.ini, tests/lib/os/image/test_glance_image.py
In case image is too large the migration fails that image was not migrated.
=> [CF-483] Wait for status of images

cloudferry/config.py, cloudferry/discover.py, cloudferry/lib/os/discovery/cinder.py, cloudferry/lib/os/discovery/glance.py, cloudferry/lib/os/discovery/keystone.py, cloudferry/lib/os/discovery/nova.py, cloudferry/lib/stage.py, punky_gibbon/install_punky_gibbon.sh, punky_gibbon/punky_gibbon/middleware.py, punky_gibbon/setup.py
Before this commit any random HTTP error (like 503) could ruin
one hour discover run. This commit add API call retrying, which
mean that in case of some non-fatal random error API request will
be repeated configured amount of times after configured amount
of time.
=> [CF-558] Add API call retrying to discover process

cloudferry/cfglib.py, cloudferry/config.py, cloudferry/discover.py, cloudferry/lib/base/resource.py, cloudferry/lib/os/discovery/cinder.py, cloudferry/lib/os/discovery/glance.py, cloudferry/lib/os/discovery/keystone.py, cloudferry/lib/os/discovery/nova.py, cloudferry/lib/os/estimation/procedures.py, cloudferry/lib/os/image/glance_image.py, cloudferry/lib/stage.py, cloudferry_devlab/cloudferry_devlab/generate_load.py, cloudferry_devlab/cloudferry_devlab/tests/base.py, cloudferry_devlab/cloudferry_devlab/tests/config.py, cloudferry_devlab/cloudferry_devlab/tests/utils.py, configs/config.ini, punky_gibbon/install_punky_gibbon.sh, punky_gibbon/punky_gibbon/middleware.py, punky_gibbon/setup.py, tests/lib/os/image/test_glance_image.py
Changelog:
- CF-562 Add debug logs to generate_load.
- [CF-558] Add API call retrying to discover process
- [CF-483] Wait for status of images
=> Release 2016-07-07

cloudferry/cli/base.py, cloudferry/config.py, cloudferry/discover.py, cloudferry/lib/os/clients.py, cloudferry/lib/os/cloud_db.py, cloudferry/lib/stage.py, cloudferry/lib/utils/remote.py
This patch add error log messages that will help to find error in
configuration.
=> [CF-424] Improve error reporting

cloudferry_devlab/requirements.txt, requirements.txt
Resolves oslo.utils version conflict
=> CF-578 oslo.utils version conflict

cloudferry_devlab/requirements.txt
=> CF-588 Some Functional Tests being skipped

cloudferry/actions/block_storage/migrate_volumes.py, cloudferry/actions/helper/task_transfer.py, cloudferry/lib/copy_engines/base.py, cloudferry/lib/os/storage/plugins/copy_mechanisms.py, cloudferry/lib/os/storage/plugins/nfs/generic.py, cloudferry/lib/utils/files.py, tests/lib/copy_engines/test_base.py, tests/lib/utils/test_files.py
Checks if destination has enough space before attempting to copy data
instead of failing in the middle of the process.
=> CF-580 Check available space before copying data

cloudferry_devlab/cloudferry_devlab/generate_load.py, cloudferry_devlab/cloudferry_devlab/tests/config.py
Added SWIFT_TESTING_ENABLED variable to config.py
=> CF-600 Make swift generation optional in generate_load and tests.

cloudferry_devlab/requirements.txt
Fixed test-generator dependecy.
=> CF-605 Fix cloudferry_devlab reqiurements: test-generator.

cloudferry/actions/filter/get_filter.py, cloudferry/lib/os/compute/nova_compute.py
Improves migration speed for user quotas by removing unnecessary API
requests.
=> CF-602 User quota migration speedup

cloudferry/lib/utils/qemu_img.py
Under some circumstances qemu-img may returin invalid JSON object which
breaks migration of ephemeral storage.
=> Invalid JSON from qemu-img

cloudferry_devlab/cloudferry_devlab/tests/config.py, cloudferry_devlab/cloudferry_devlab/tests/functional_test.py
Added logging handler for functional tests.
=> CF-601 Disable logging to stdout during functional tests execution.

cloudferry/lib/os/storage/plugins/copy_mechanisms.py
This measure improve write speed to VMAX volumes 7 times.
=> [CF-632] Set default blocksize for dd to 64k

cloudferry/actions/compute/transport_instance.py
In case ephemeral storage fails to migrate for any reason it would
lead to a non-descriptive traceback. This was caused by incorrect
object being passed to migration state tracking subsystem and
resolved with this patch.
=> CF-640 Ephemeral migration failure

cloudferry/cli/v1/commands.py, cloudferry/lib/os/storage/cinder_db.py, cloudferry/tools/mark_volumes_deleted.py, setup.cfg
Modify a database of a source cloud to mark the volumes as deleted.
=> [CF-636] Mark volumes on source cloud as deleted

cloudferry/actions/block_storage/migrate_volumes.py, cloudferry/lib/utils/override.py, cloudferry_devlab/cloudferry_devlab/generate_load.py, cloudferry_devlab/cloudferry_devlab/tests/config.py
Extend generate load to add cinder volume types.
=> [CF-612] Creating cinder volume types

cloudferry/cli/shell.py, cloudferry/cli/v2/commands.py, cloudferry/config.py, cloudferry/discover.py, cloudferry/lib/os/clients.py, cloudferry/lib/os/cloud_db.py, cloudferry/lib/os/discovery/cinder.py, cloudferry/lib/os/discovery/keystone.py, cloudferry/lib/os/discovery/neutron.py, cloudferry/lib/os/discovery/node.py, cloudferry/lib/os/discovery/nova.py, cloudferry/lib/os/discovery/stages.py, cloudferry/lib/os/migrate/base.py, cloudferry/lib/os/migrate/glance.py, cloudferry/lib/os/migrate/keystone.py, cloudferry/lib/utils/override.py, cloudferry/lib/utils/remote.py, cloudferry/lib/utils/taskflow_utils.py, cloudferry/model/__init__.py, cloudferry/model/compute.py, cloudferry/model/identity.py, cloudferry/model/network.py, cloudferry/model/storage.py, tests/test_config.py
Several improvements to new version of migration tooling which include discovery of new stuff, bug fixes and new features that would help writing complex migrations.
=> Improvements to migration v2

Dockerfile, README.md
Installation instructions were not detailed and clear enough which
resulted in different kinds of problems.
=> Update installation instructions

cloudferry/lib/os/compute/nova_compute.py, cloudferry/lib/os/identity/keystone.py
Quota migration failed with KeyError traceback because it was trying to
access quotas for non-existing tenant.
=> CF-648 KeyError during quota migration

cloudferry/actions/block_storage/attach_used_volumes_via_compute.py
If volume fails to attach to VM for any reason, report would contain
two entries for the same VM:
```
| 2.3 | VM | server2 (<id>) | <dst_id> | success    | None             |
| 2.4 | VM | server2 (<id>) | None     | incomplete | Cannot attach
volume 'f1b16b58-ebc5-4b55-be16-f584978a350c' to VM 'server2': volume
does not exist |
```
The patch resolves the problem by correctly associating VM
migration status in report.
=> CF-642 Incomplete migrations of attached volumes report failures
